### ISSUE TITLE
[水位站infobox]電池電壓物理量介接

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#102]
電池電壓物理量介接

**Comment by flyingapsara** [comment]
之前API未提供電池電壓的歷線
只有即時數值

**Comment by karateboy** [comment]
目前抓到的還是舊的資料
![image](https://user-images.githubusercontent.com/1067042/79119914-10f86e00-7dc4-11ea-9afe-eed37002260d.png)

**Comment by karateboy** [comment]
fixed 0413
