### ISSUE TITLE
[淹水感測infobox]新增「通訊方式」物理量、警戒值修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#107]
新增淹水感測器「通訊方式」物理量。
範例：
通訊方式：NB-IOT

![image](https://user-images.githubusercontent.com/28863560/77903356-4d50a800-72b5-11ea-93dc-de072cf1c6d2.png)
警戒值請抓各測站設定值(目前所有測站都是15、25、30)
告知/通知/告警

**Comment by flyingapsara** [comment]
API 需增加欄位
下週提供

**Comment by EideWang** [comment]
先移除一、二級警戒假的示意
之後要接告知/通知/告警API

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/78849765-f894f600-7a47-11ea-9d70-58126b4376d8.png)

警戒值錯誤

**Comment by karateboy** [comment]
把假的警戒線先移除

**Comment by karateboy** [comment]
fixed 0420

**Comment by EideWang** [comment]
尚未看到"通訊方式"及"預警、警戒、危險"被加入

**Comment by karateboy** [comment]
@Elvis0059 相關警戒值API出來後請告知.

**Comment by EideWang** [comment]
已出API

**Comment by karateboy** [comment]
fixed 0504
