### ISSUE TITLE
所附網址為客戶反饋之頁面意見，再請協助調整設計。

### ISSUE THREAD

**Issue by flyingapsara** [karateboy/ylfs_demo#11]
https://docs.google.com/document/d/1UH9kz8YEXGLoxRQKNmaKTwbzOa6ts9xiSVixh_TaIyg/edit#

**Comment by karateboy** [comment]
確認反饋意見已經拆分為個別issue, 則此issue建議關閉

**Comment by PerryWu** [comment]
close as duplicated issue
