### ISSUE TITLE
[路面淹水警戒-警戒資訊]警戒順序調整及文字說明

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#112]
工作項目(七)、4.和5.和17.

警戒表格新增「資料異常」欄位，判定方式為{最近一筆淹水高度資料，若>=5cm，則計算資料更新時間是否超過15分鐘；若<5cm，則計算資料更新時間是否超過75分鐘。超過判定為斷線}

警戒表格警戒順序調整為{告警/通知/告知/反應/資料異常}

「警戒資訊」表格新增各警戒項目之文字說明：
	告警(淹水深度>30cm)：通知鄉鎮市公所或村里長至現場警示及疏散現場，並通知道路管理單位禁止通行
	通知(淹水深度>25cm)：通知村里長至低窪地區警示住戶及通知道路管理單位進行管制出入及設置警示號誌
	告知(淹水深度>15cm)：通知村里長至低窪地區住戶及道路實施防範積淹水措施
	資料異常：最近一筆感測資料未即時更新。

**Comment by karateboy** [comment]
fixed 0401
