### ISSUE TITLE
[CCTV斷線通知] 點擊表格測站未直接彈出該測站資訊

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#114]
工作項目(八)、1.
「CCTV斷線警告」文字改成「CCTV斷線通知」，表格上出現之測站名稱，可直接點擊後彈出該測站infobox(斷線通知視窗將被關閉)，並於地圖上移動到該測站位置。

**Comment by karateboy** [comment]
fixed in 0405
