### ISSUE TITLE
[CCTV infobox] infobox調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#115]
![image](https://user-images.githubusercontent.com/28863560/77904674-88ec7180-72b7-11ea-8e06-52dc1eab2af1.png)
1. 移除權責單位
2. 2*2畫面以不要出現scroll bar為大小限制(業主一期要求不要下滑，要一次能看四張)

**Comment by EideWang** [comment]
另，業主反應，經緯度跟資料時間應該要是並排呈現

**Comment by karateboy** [comment]
影像以原始大小呈現, 若業主需要放大. 請自行調整瀏覽器放大比例. (Ctrl+'+')
