### ISSUE TITLE
[水位警戒] 水位警報通知紀錄_缺少水位警報查詢功能

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#125]
工作項目(六)、9.
 水位警報通知紀錄，具時間區間查詢、警報類別查詢{查詢全部/溢堤警戒/一級警戒/二級警戒/資料異常}。水位警報通知紀錄表格欄位包含{警報名稱、來源測站、發布時間}。

**Comment by karateboy** [comment]
Fixed UI. backend API pending...
