### ISSUE TITLE
[路面淹水警戒] 路面淹水警報通知紀錄_缺少警報類別查詢

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#126]
工作項目(七)、6.
「路面淹水警報通知紀錄」，具時間區間查詢、警報類別查詢{反應(淹水深度>5cm)/告知(淹水深度>15cm)/通知(淹水深度>25cm)/告警(淹水深度>30cm)/資料異常/查詢全部}，表格欄位包含{警報名稱、來源測站、發布時間}。

**Comment by karateboy** [comment]
fixed UI. No backend API yet...
