### ISSUE TITLE
[天氣概況] 文字描述API抓的內容不齊全

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#129]
![image](https://user-images.githubusercontent.com/28863560/78515711-6ee7ed00-77e9-11ea-9ab5-aea94f60afca.png)

目前只抓到第一句"東北季風及華南雲雨區東移影響，陰時多雲短暫陣雨或雷雨，早晚較涼，沿海空曠地區易有強陣風，外出請帶雨具。"

須分段顯示各句描述

**Comment by karateboy** [comment]
各句都顯示時版面會變得過長
建議還是向中央氣象局那樣只顯示第一句
![image](https://user-images.githubusercontent.com/1067042/78521997-71a10d00-77fe-11ea-8ad5-655c3992bd1e.png)

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/78522013-7fef2900-77fe-11ea-8572-3cbd439e2734.png)

**Comment by EideWang** [comment]
@karateboy 還是需要每句都顯示，讓下面太陽月亮雲的圖示小一些，再調整排版

**Comment by karateboy** [comment]
fixed 0407
