### ISSUE TITLE
[水位站infobox] 水位歷線數值介接即時水位

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#130]
![image](https://user-images.githubusercontent.com/28863560/78515913-414f7380-77ea-11ea-9331-3c7d898a9c02.png)
不清楚目前是否是假的數值展示，因為圖形和即時數據對不上

**Comment by karateboy** [comment]
假的....只有雨量歷線是真的

**Comment by karateboy** [comment]
fixed 0413

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/79175790-3a031800-7e31-11ea-846e-24cb09e89204.png)
@karateboy  目前看水位歷線仍然是假的數值

**Comment by karateboy** [comment]
fixed in 0414

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/79308835-e3c6cf80-7f2b-11ea-8f6d-4f883e9ef758.png)
@karateboy  目前highchart沒有顯示內容

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/79309286-a1ea5900-7f2c-11ea-9fc2-e82af0c5da94.png)

顯示了，但是切換測站時，圖表內容沒有跟著換
電池電壓作圖也怪怪的

**Comment by karateboy** [comment]
@Zunnex API資料傳輸速度太慢...目前還沒有電池電壓歷史資料?

**Comment by karateboy** [comment]
沒改程式  但看起來後台API已經修正...

**Comment by karateboy** [comment]
fixed 0417
