### ISSUE TITLE
[水位警戒] 點擊警戒表格內測站，直接彈出對應的infobox並移動到該點位置

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#133]
工作項目(六)、7.
於警戒表格上出現之測站名稱，可直接點擊後彈出該測站infobox(警戒表格將被關閉)，並於地圖上移動到該測站位置。

**Comment by karateboy** [comment]
fixed 0406

**Comment by EideWang** [comment]
@karateboy  目前測試功能不見了 V0407

**Comment by karateboy** [comment]
改正github 沒check in issue. 
fixed in 0408

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/78847469-74d80b00-7a41-11ea-8f83-33769c71bd7c.png)
@karateboy 目前點了只有title會換

**Comment by karateboy** [comment]
fixed 0410
