### ISSUE TITLE
[淹水感測infobox] 歷線圖呈現修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#135]
![image](https://user-images.githubusercontent.com/28863560/78517006-3565b080-77ee-11ea-95b8-cb1f7670ea25.png)

針對淹水高度，0要貼X軸，不要懸空

另外打問號的部分，能否在未顯示電池電壓和訊號強度時，不要有座標軸出現呢?(有顯示才出現軸)

**Comment by EideWang** [comment]
另，"前24小時淹水歷史" 文字麻煩修改為"淹水深度"
"淹水高度"都修正為"淹水深度"(藍框跟Y軸)

**Comment by karateboy** [comment]
@Zunnex 座標軸無法選擇性顯示唷.

**Comment by EideWang** [comment]
提醒一下還是要修正"0要貼X軸，不要懸空"

**Comment by karateboy** [comment]
fixed 0408
