### ISSUE TITLE
[總覽] 防汛平台重新整理功能

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#137]
![image](https://user-images.githubusercontent.com/28863560/78520492-567fce80-77f9-11ea-8e9c-693883d32cd1.png)
目前點擊重新整理會跳出對話框，然後會返回到登入畫面
請修正為重新整理後直接重新整理該頁面
例如登入後為https://yliflood.yunlin.gov.tw/iflood/weatherSummary
點擊重新整理後，依然是https://yliflood.yunlin.gov.tw/iflood/weatherSummary網址，頁面依然是天氣概況彈出視窗

**Comment by karateboy** [comment]
難度太高  無法

**Comment by flyingapsara** [comment]
需要分開包成兩個不同的project才行

**Comment by karateboy** [comment]
目前改成用單一project, refresh後. 若已經登入, refresh會/platform或/iflood

**Comment by karateboy** [comment]
fixed 0421
