### ISSUE TITLE
[天氣概況]NCDR累積降雨圖調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#139]
![image](https://user-images.githubusercontent.com/28863560/78520847-88456500-77fa-11ea-88d3-c2ed54bb50ac.png)

Title請改為"NCDR累積雨量圖"
請加上中文說明(目前圖片上有英文的累積幾小時文字，但太小不清楚)
依1、2、3、6、12、24小時這六張圖片切換，分別配上
"1小時累積雨量"
"2小時累積雨量"
"3小時累積雨量"
"6小時累積雨量"
"12小時累積雨量"
"24小時累積雨量"

**Comment by karateboy** [comment]
fixed 0406
