### ISSUE TITLE
[總覽] 彈出視窗關閉問題

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#142]
關閉方式：
1. 按叉叉
2. 點地圖
3. 點測站orButton(會彈出新視窗取代之)
4. 點選主控台中九個主項目(天氣概況、雨量資訊、水位資訊......等，有彈出新視窗的會是取代，沒有的就是直接關閉)
5. 點選"主控台"、"圖層"、"系統管理"
6. 測站取消勾選時(關閉infobox)

**Comment by karateboy** [comment]
造成程式過度複雜  其中2,3,4不可行,  
只做1 6

**Comment by EideWang** [comment]
只做4、5

**Comment by karateboy** [comment]
fixed 0413
