### ISSUE TITLE
[總覽] 打開列表會連動影響問題

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#144]
![image](https://user-images.githubusercontent.com/28863560/78522108-d2304a00-77fe-11ea-9699-330d8128dcb8.png)
![image](https://user-images.githubusercontent.com/28863560/78522117-db211b80-77fe-11ea-8d97-461670256954.png)

目前測試假如打開任一主項目下的樹幹
切換到其他主項目時，旗下的對應排序的樹幹也會被展開
請修正為獨立開啟，不要連動影響

另，每次點擊進入任一主項目時，其下的樹狀結構須重置狀態
目前發現假如曾點擊某一測站，再次進入該主項目時，該測站仍是被勾選狀態(但實際上還沒點勾選)
![image](https://user-images.githubusercontent.com/28863560/78522250-58e52700-77ff-11ea-9470-390db5dcb68c.png)

**Comment by karateboy** [comment]
fixed 0407
