### ISSUE TITLE
[系統管理-自主防災社區管理&滯洪池管理] 目前無法針對row進行刪除

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#148]
![image](https://user-images.githubusercontent.com/28863560/78522708-de1d0b80-7800-11ea-9eeb-02dd11f1d7b3.png)

![image](https://user-images.githubusercontent.com/28863560/78522773-11f83100-7801-11ea-852c-803c0a2591f9.png)

有新增欄位功能，但缺少移除某一列的功能

**Comment by karateboy** [comment]
fixed in 0406
