### ISSUE TITLE
主控版、按鈕、視窗間距調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#16]
主控版再縮小，目前文字、按鈕間的空白處太多，整體看起來鬆散
各div邊界間距間格大小須固定，內容、文字需對齊，使整體看起來不會凌亂無章
![image](https://user-images.githubusercontent.com/28863560/69930162-eedd0e00-14fc-11ea-8366-c10c0585560a.png)

按鈕內icon與文字不因窄縮而分行，文字若須斷行排版須配合文意連貫

彈出視窗內間隔需注意，此間隔也需與整個網站的間隔大小都統一。(所有的model都一樣)
![image](https://user-images.githubusercontent.com/28863560/69930168-fd2b2a00-14fc-11ea-9b54-6a2c75d6718a.png)

**Comment by karateboy** [comment]
> 按鈕內icon與文字不因窄縮而分行，文字若須斷行排版須配合文意連貫

請問如何做? 現有技術無法做到!
