### ISSUE TITLE
[天氣概況] 破版問題、版面調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#161]
![image](https://user-images.githubusercontent.com/28863560/78758842-562a3380-79b1-11ea-9b63-7f02bfc598dd.png)

A. 目前有破版問題
B. 再調整版面，下排圖/動圖的高要齊高

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/78759425-2cbdd780-79b2-11ea-821b-63a00b9249e7.png)

1. 天氣警特報下，沒有警特報時的文字請更改為"目前無警特報"
2. 星期跟日期分段展示，避免有的同一行有的卻不同
3. 文字、圖示行高置中呈現

**Comment by karateboy** [comment]
fixed 0410

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/79084999-605d8080-7d69-11ea-9a8c-1fa8e2a391c0.png)
目前看破版問題仍存在

**Comment by karateboy** [comment]
我的螢幕解析度測不出來1920x1024....
我們應該定義螢幕最佳解析度比方說就1920x1024. 有放大無放大.
要不然真的很難所有的解析度通通都照顧到完美

**Comment by karateboy** [comment]
fixed 0413
