### ISSUE TITLE
[CCTV infobox] 固定影像大小

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#162]
![image](https://user-images.githubusercontent.com/28863560/78849553-5aa12b80-7a47-11ea-81d0-ce69a2fd0dd0.png)

不固定而採用原始大小的話，會出現這種問題
請依視窗大小設定調整固定的影像圖片長寬

**Comment by karateboy** [comment]
max-width:361px
fixed 0412

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/79084854-b5e55d80-7d68-11ea-9cb5-89a2b2125d04.png)
 目前看問題仍存在，請C哥再確認一下

**Comment by karateboy** [comment]
fixed 0413
