### ISSUE TITLE
[單一入口網] RWD

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#164]
工作項目(二)、6.
UI設計調整及美化(含RWD)

**Comment by karateboy** [comment]
fixed 0415

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/79406717-64d4a400-7fca-11ea-96cf-dfeeb75cde27.png)
@karateboy 
A. 排字調整
B. 被削掉一部份
C. 無法下拉

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/79406991-fe03ba80-7fca-11ea-86c8-de2375129f93.png)

收合紐在網頁版時不出現
LOGO置左，調整字體大小
選單內容滿畫面

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/79409034-710f3000-7fcf-11ea-9031-7d51b620ab4d.png)
我是好的

**Comment by karateboy** [comment]
fixed 0416

**Comment by karateboy** [comment]
做了一些調整

**Comment by karateboy** [comment]
再試看看吧  有再改進一些

**Comment by karateboy** [comment]
fixed 0425
