### ISSUE TITLE
[單一入口網] 資料修改-欄位

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#166]
![image](https://user-images.githubusercontent.com/28863560/78851124-9e962f80-7a4b-11ea-9149-939476a05363.png)

目前切版仍須調整

工作項目(二)、2.
使用者基本資料修改功能，包括使用者名稱、密碼、頭像照片上傳/刪除、部門{防洪維護科、水利工程科、水利行政科、水土保持科、下水道科}

另，業主後來有說要再多開一個"Email欄位"

**Comment by EideWang** [comment]
@flyingapsara @Elvis0059  提醒一下工作項目(二)、2.和(二)、3.均多一項Email欄位

**Comment by karateboy** [comment]
fixed 0410

**Comment by karateboy** [comment]
fixed 0414
