### ISSUE TITLE
[單一入口網] 使用者管理-欄位

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#167]
![image](https://user-images.githubusercontent.com/28863560/78851526-8bd02a80-7a4c-11ea-9d4f-a0b1e1e2cc85.png)

目前版面欄位與工作項目(二)、3.仍有所落差
 使用者管理功能(管理者帳號可查看/管理所有其他使用者帳號，包括使用者名稱變更、密碼變更、頭像照片變更、部門變更)

注意業主後來多要求加入"Email"欄位

**Comment by karateboy** [comment]
fixed 0410

**Comment by karateboy** [comment]
尚未整合後台api

**Comment by karateboy** [comment]
fixed 0414
