### ISSUE TITLE
[普通]雨量警戒>即時報表 欄位排版

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#17]
![image](https://user-images.githubusercontent.com/28863560/69935832-fc9c8e80-1510-11ea-85cd-3e58f61fd38a.png)
將table內的thead中的過去累積分成上下兩列，第一列寫「過去累積」，第二列寫各累積小時(如圖)。title文字盡量不要直書。

**Comment by karateboy** [comment]
無法....螢幕解析度有限, 要放的字太多.

**Comment by flyingapsara** [comment]
若有如此考量
可以先不硬將文字直書

**Comment by karateboy** [comment]
建議把"累積" 從欄位去掉...modal再放大

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/70856638-665a6680-1f1b-11ea-9f9e-9175ea05a43c.png)

**Comment by karateboy** [comment]
fixed in 0.1.1215

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/70878407-42bb1d00-1ffc-11ea-8e72-3317b3ebe0d9.png)
欄位名稱呈現未修正為適合閱讀的格式
