### ISSUE TITLE
[優化] 地圖點擊測站時，主控板內測站選項未跟著連動

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#173]
![image](https://user-images.githubusercontent.com/28863560/79085837-918b8000-7d6c-11ea-91c5-775503ed6e98.png)

如圖中勾選崙背站為例，地圖點擊彈出infobox後，樹狀結構內的崙背沒有呈現打勾狀態

**Comment by karateboy** [comment]
fixed 0418
