### ISSUE TITLE
[系統管理]水位警戒管理功能實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#177]
註：此項目不包含中央管水位站(不用管中央管水位站)

**Comment by karateboy** [comment]
fixed 0417

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/79552859-32ac6a80-80ce-11ea-8195-91b9672a196a.png)

許多空值，有問題，也無法編輯
Error: Request failed with status code 400

**Comment by karateboy** [comment]
API回傳有問題的站已經標成disabled 無法編輯. 關掉此issue, 重開一個bug issue
