### ISSUE TITLE
[系統管理]自主防災社區管理 功能實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#179]
![image](https://user-images.githubusercontent.com/28863560/79097622-cc081380-7d92-11ea-88ad-96c926d02dc2.png)

由於自主防災社區跟滯洪池這兩項比較特別，新增項目時會連帶影響地圖上打點新增，所以需要再多開"經度"、"緯度"的欄位

**Comment by karateboy** [comment]
fixed 0430
