### ISSUE TITLE
水位警戒>即時報表 表格欄位調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#18]
![image](https://user-images.githubusercontent.com/28863560/69935908-38cfef00-1511-11ea-8e8d-ec42608f4cdf.png)
若表格title內文字需換行，需換在較好的定點，使得語意更好閱讀。並建議將title文字置中。
若表格有因為文字放不下的考量，可調整modal大小。手機版table建議使用js將table更好閱讀。

**Comment by karateboy** [comment]
極度困難.....現有技術無法實作

**Comment by flyingapsara** [comment]
換行可使用<br/>即可
modal的大小再視情況
要必免文字換行的話可以使用 white-space: nowrap;

手機版table就先放著，未來有時間再行優化，可先用 responsive-table (scroll的方式) 來實作
是bootstrap的元件

**Comment by karateboy** [comment]
謝謝...

**Comment by karateboy** [comment]
目前看起來還ok...
![image](https://user-images.githubusercontent.com/1067042/70534946-0ec49f80-1b97-11ea-81ee-716105d72b3f.png)
