### ISSUE TITLE
[系統管理] 移動式抽水機管理 功能實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#183]
![image](https://user-images.githubusercontent.com/28863560/79098156-ebec0700-7d93-11ea-94e0-99b691241071.png)

同抽水站管理， 須新增"取消"功能鍵

另，圈起來的這兩個row，他們是同一個單位叫做 "四湖-林業試驗所"

**Comment by karateboy** [comment]
fixed 0430
