### ISSUE TITLE
[歷史雨量資料] 歷史雨量預報 頁面功能實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#189]
查詢全部鄉鎮市
	時間區間選擇
	EXCEL表格下載功能
	表格呈現，欄位包含{行政區、時雨量、1小時預測雨量(mm)、2小時預測雨量(mm)、3小時預測雨量(mm)、4小時預測雨量(mm)、5小時預測雨量(mm)、6小時預測雨量(mm)、資料時間}

查詢單一鄉鎮市
	時間區間選擇
	鄉鎮市選擇(下拉式選單)
	下拉式選單功能，測項包括{時雨量、1小時預測雨量(mm)、2小時預測雨量(mm)、3小時預測雨量(mm)、4小時預測雨量(mm)、5小時預測雨量(mm)、6小時預測雨量(mm)}
	測項柱狀圖，附JPG下載功能
	EXCEL表格下載功能
	表格呈現，欄位包含{行政區、時雨量、1小時預測雨量(mm)、2小時預測雨量(mm)、3小時預測雨量(mm)、4小時預測雨量(mm)、5小時預測雨量(mm)、6小時預測雨量(mm)、資料時間}

**Comment by karateboy** [comment]
歷史雨量預報不是沒了?

**Comment by EideWang** [comment]
@karateboy  雨量預報跟水位預報都規劃整合在"歷史雨量資料" 跟 "歷史水位資料" 頁籤中
其中雨量的累積跟預報因為來源不同，所以切兩個子頁籤
水位則是來源相同，所以不需切兩個子頁籤

**Comment by karateboy** [comment]
@Zunnex
先提供 單一測站查詢方式
全測站須待API 協助
建議先關掉 另開issue 修這個問題
