### ISSUE TITLE
[水位警戒] 水位infobox的狀態有誤

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#197]
![image](https://user-images.githubusercontent.com/28863560/79177376-48ebc980-7e35-11ea-82d3-d5534f46578f.png)

目前看來警戒狀態沒有接上，請C哥確認，謝謝

**Comment by karateboy** [comment]
@Elvis0059 狀態目前是後端API送的. 麻煩檢查一下

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/80285112-40f52900-8755-11ea-9d52-518baf05f633.png)

**Comment by karateboy** [comment]
看起來好像已經串接上了
