### ISSUE TITLE
[警戒管理] 須設定A < B限制式

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#200]
![image](https://user-images.githubusercontent.com/28863560/79552550-c3367b00-80cd-11ea-9f64-2117f56040ce.png)

雖然DB一樣可以被修改，但會出BUG
![image](https://user-images.githubusercontent.com/28863560/79552617-d6494b00-80cd-11ea-8396-a43dbf2942a4.png)

**Comment by EideWang** [comment]
淹水警戒管理 A<B<C
雨量警戒管理 (1/3/6)小時的二級警戒數值要小於一級警戒數值
水位警戒管理 二級<一級<溢堤

**Comment by karateboy** [comment]
fixed 0430
