### ISSUE TITLE
[優化] 水位站樹幹內容依名稱排序

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#205]
目前排列呈現方式過於凌亂，需依名稱排序
![image](https://user-images.githubusercontent.com/28863560/79556908-48bd2980-80d4-11ea-891d-32ed5efa984c.png)

例如
舊虎尾溪排水一
舊虎尾溪排水二
舊虎尾溪排水三
舊虎尾溪排水四
.
.
.

**Comment by karateboy** [comment]
這是中文排序無解的老問題. 完整故事可以參考
https://blog.darkthread.net/blog/javascript-chinese-char-sorting/

結論是沒有好的解決方法. 因為是以"漢語拼音"當作順序

**Comment by karateboy** [comment]
改以"站碼" 排序看起來效果還不錯
fixed 0419

**Comment by EideWang** [comment]
解的漂亮！
