### ISSUE TITLE
潮位站/中央站 voltage為null

### ISSUE THREAD

**Issue by karateboy** [karateboy/ylfs_demo#212]

**Comment by Elvis0059** [comment]
中央管跟潮位站只有水位，沒有電池電壓。

**Comment by flyingapsara** [comment]
已處理

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/80983921-c072ae80-8e5f-11ea-8b11-3571fcd53073.png)
Voltage 是null

**Comment by karateboy** [comment]
fixed 0505
