### ISSUE TITLE
[UI優化] 雨量站infobox

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#216]
![image](https://user-images.githubusercontent.com/28863560/79930530-562f3680-847b-11ea-9243-36e04e5bace6.png)

調整highchart佔比，業主反應作圖區文字太小看不清楚，希望放大
整個infobox字型與平台統一
![image](https://user-images.githubusercontent.com/28863560/79931975-eae76380-847e-11ea-9df7-1f2798ae1460.png)
重點呈現區版面麻煩再美化，業主的美化比照標準參考如下(僅參考，不是要排成下面那樣)
![image](https://user-images.githubusercontent.com/28863560/79932073-3863d080-847f-11ea-8b66-11e27abb3392.png)

**Comment by karateboy** [comment]
字型改成14px 黑體字
