### ISSUE TITLE
[權限設定] 非管理者帳號在系統管理所見選項修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#218]
![image](https://user-images.githubusercontent.com/28863560/79951902-22203980-84ac-11ea-951c-d30c35627e4e.png)

非管理者帳號，應設定僅看見未被劃掉的button

**Comment by karateboy** [comment]
fixed 0422

**Comment by EideWang** [comment]
隱藏反了

**Comment by karateboy** [comment]
fixed 0422
