### ISSUE TITLE
[水位infobox] 警戒值要跟"水位"是共用Y軸上限的

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#220]
![image](https://user-images.githubusercontent.com/28863560/79972734-f95a6d00-84c8-11ea-8b0d-a5ccde97ca85.png)

目前default顯示"水位"，當水位太低時，圖上看不到警戒值
做圖上警戒值需要常存

**Comment by karateboy** [comment]
fixed 0422
