### ISSUE TITLE
[水位infobox] highchart電壓點擊後沒有顯示在圖上

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#221]

**Comment by karateboy** [comment]
因為電壓在上方....

**Comment by karateboy** [comment]
先前要求水位要顯示警戒線...但水位低於警戒線時, 就不會顯示.
若設定Y軸最大值時, 電壓又可能不會顯示.
與其如此, 建議還是讓Highchart自動判斷

**Comment by EideWang** [comment]
水位跟水位警戒包一組，電壓自己一組
所以當隱藏水位時，水位警戒也會被隱藏
default顯示水位時，highchart做圖會畫四條線：水位、二級警戒、一級警戒、溢堤警戒
不知這樣是否可行呢?
