### ISSUE TITLE
[UI優化] 雨量警戒表格&鄉鎮地圖

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#227]
![image](https://user-images.githubusercontent.com/28863560/80337123-b6631580-888b-11ea-825d-9c2b557790d2.png)
![image](https://user-images.githubusercontent.com/28863560/80337138-bebb5080-888b-11ea-8de7-8c8a22676287.png)

表格與地圖要齊高，地圖佔比可再多
表格部分因未顯示上最多也就只有20個item(鄉鎮市)，表格欄未配置及字體大小可再縮小

**Comment by karateboy** [comment]
fixed 0507
