### ISSUE TITLE
[UI優化] 移動式抽水機智慧調度 表格優化

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#232]
![image](https://user-images.githubusercontent.com/28863560/80337450-74869f00-888c-11ea-9890-db18ea351a43.png)

接模式API前，麻煩C哥先做UI美化，因為5/7就要先出報告假畫面，感謝

**Comment by karateboy** [comment]
fixed 0505

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81131818-04100a00-8f7f-11ea-88af-28c0e4b1dfec.png)

欄位需切成
![image](https://user-images.githubusercontent.com/28863560/81131872-3d487a00-8f7f-11ea-991a-bef330d1b7c6.png)

**Comment by EideWang** [comment]
另外，截圖的這個表格區塊，不需有排序(上下箭頭)功能，因為規劃上是固定順序項目

**Comment by karateboy** [comment]
fixed 0506

**Comment by karateboy** [comment]
修好了
