### ISSUE TITLE
[雨量資訊] 雨量預報6個圖層套疊實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#235]
![image](https://user-images.githubusercontent.com/28863560/80445443-e02d4280-8946-11ea-9172-76f1385bc12a.png)

請問目前卡哪個部份呢?

**Comment by karateboy** [comment]
資料圖檔？

**Comment by flyingapsara** [comment]
@karateboy  @Zunnex 
此項目如 4/27 早上會議中安排的
於五月第一週實作
屆時會以API方式提供各對應的nc檔圖層對應連結供c哥前端處理

**Comment by Elvis0059** [comment]
API已上線，若wms後續需調整，再另開issue。
