### ISSUE TITLE
系統管理 > scroll bar區域超出主控版範圍，且切換時與其他主控版頁面有版面寬度差異變動

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#24]

**Comment by EideWang** [comment]
此外，目前雨量、水位、防汛工具等下方展開時，均發現略微超過主控版範圍

**Comment by karateboy** [comment]
這就是昨天討論的問題, 上方區域是變動. 下方長度也無法得知. 若給固定長度, 結果就是有時太長, 有時太短. 請看Gmail也是使用從頭到尾的scroll bar. 
![image](https://user-images.githubusercontent.com/1067042/70490367-1a817900-1b39-11ea-8bf3-be47c8f12cd0.png)

給上方按鈕固定大小, 結果就是上方可能顯示不全或同樣有scroll bar. 這樣效果更不好

**Comment by karateboy** [comment]
需要更完整的討論....這期不修正
