### ISSUE TITLE
[防汛工具] 移動式抽水機 實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#241]
以"組織"作為樹幹分類，組織->抽水機編號
infobox title為"組織"+" "+"抽水機編號"
infobox欄位：經緯度、口徑大小(英吋)、抽水量(CMS)、電力、網路、通訊、監測功能、保管人員、
保管人員聯絡方式、存放位置、備註

**Comment by karateboy** [comment]
fixed
