### ISSUE TITLE
[防汛工具] 抽水站 放大鏡 未做成表格

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#248]
![image](https://user-images.githubusercontent.com/28863560/80663600-00840b00-8ac7-11ea-88d7-cc2b2c227426.png)

目前仍聯動展示成系統管理視窗，需做成表格(附EXCEL下載)

**Comment by karateboy** [comment]
fixed 0503

**Comment by karateboy** [comment]
fixed 0504
