### ISSUE TITLE
[防汛工具] 水閘門、防潮閘門 放大鏡 未做成表格

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#249]
![image](https://user-images.githubusercontent.com/28863560/80663710-5ce72a80-8ac7-11ea-89b0-04757bbed4de.png)

目前仍聯動展示系統管理視窗
需做成表格(附EXCEL下載)

**Comment by karateboy** [comment]
fixed 0502

**Comment by karateboy** [comment]
fixed 0504
