### ISSUE TITLE
[系統管理] 移動式抽水機管理 欄位修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#250]
![image](https://user-images.githubusercontent.com/28863560/80663962-0cbc9800-8ac8-11ea-890e-13eb470e8136.png)

"合計"欄不會在系統管理表格出現，應在放大鏡表格下方，以自動加總上面各列數值的方式展示

**Comment by karateboy** [comment]
@Elvis0059 API有合計資料

**Comment by karateboy** [comment]
fixed 0502
