### ISSUE TITLE
[防汛工具] 移動式抽水機 放大鏡 未做成表格

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#251]
![image](https://user-images.githubusercontent.com/28863560/80664061-4beae900-8ac8-11ea-8de0-3c892f119edd.png)

目前仍聯動展示系統管理視窗
需做成表格(附EXCEL下載)
最後一列"合計"須加總上面各列數值

**Comment by karateboy** [comment]
@Elvis0059  API中包含"合計"

**Comment by karateboy** [comment]
fixed 0504

**Comment by karateboy** [comment]
fixed 0504
