### ISSUE TITLE
[系統管理] 未點擊"儲存"便會自動儲存的BUG、刪除需有確認視窗

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#252]
目前測試，歷史圖資管理、歷史報表管理、相關連結管理
編輯欄位時，沒點擊儲存便自動儲存了(修改後直接關閉視窗也會儲存)

"刪除"需有確認視窗防呆

**Comment by EideWang** [comment]
"刪除"需有確認視窗防呆
儲存BUG C哥已說明原因

**Comment by karateboy** [comment]
fixed 0603
