### ISSUE TITLE
[優化] 大溝支線抽水站 CCTV圖示關不掉

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#253]
![image](https://user-images.githubusercontent.com/28863560/80681188-bd3f9180-8af2-11ea-93e4-344bc49591e4.png)

**Comment by EideWang** [comment]
大溝支線抽水站 在水林鄉跟口湖鄉都有，目前會出BUG，兩站都抓到相同影像Url

**Comment by karateboy** [comment]
這是CCTV測站名相同造成的問題... 需要uuid

**Comment by Elvis0059** [comment]
API新增uuid，請確認。

**Comment by karateboy** [comment]
fixed 0525
