### ISSUE TITLE
[淹水感測infobox] 電池電壓顯示位數調整、電壓highchart未正常顯示數值

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#256]
![image](https://user-images.githubusercontent.com/28863560/80930986-b44c0a00-8de9-11ea-901d-18efe1b13860.png)

電壓只顯示到小數第二位
Highchart中的電壓數值不是即時數據(未介接?)

**Comment by karateboy** [comment]
fixed 0504
