### ISSUE TITLE
[中央管水位站] highchart尚未實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#258]

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/81028745-4836d800-8eb5-11ea-8d6e-3964b4268bcc.png)

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/81028770-5e449880-8eb5-11ea-85a7-79c3888d1a40.png)

**Comment by karateboy** [comment]
後台電池電壓為null 無法查詢

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81131709-982da180-8f7e-11ea-881b-9e98c1f62d81.png)

@karateboy 目前無法顯示歷線圖，不知原因是否為API問題呢?

**Comment by karateboy** [comment]
@Zunnex 是的 API查詢水位成功 但沒有資料

**Comment by karateboy** [comment]
0511
