### ISSUE TITLE
[潮位站] highchart尚未實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#259]
![image](https://user-images.githubusercontent.com/28863560/80931550-2a05a500-8ded-11ea-84b9-a3466514addb.png)

**Comment by karateboy** [comment]
@Zunnex @Elvis0059 已經實作, 但水位無資料

**Comment by EideWang** [comment]
@karateboy 水位都能抓到即時水位資料，不知道C哥說的水位無資料是指哪個部份呢?

**Comment by karateboy** [comment]
@Zunnex 查詢成功  但無回傳資料

**Comment by karateboy** [comment]
fixed 0511
