### ISSUE TITLE
[優先]單一入口整合平台頁面待實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#26]
![image](https://user-images.githubusercontent.com/28863560/70486368-85788300-1b2c-11ea-85ad-96cad1adfa39.png)
1. 系統管理平台呈現+選擇進入其他決策平台之功能(目前只會有2個，就是我們做的智慧防汛整
合平台，外加一個「雲端水情圖資整合平台
http://210.61.11.57/yunlinWRD3/gee/user/index.php?」
2. 左側快速選單先刻假頁面(文字寫死)，「相關網站」、「自主檢查表」不須製作

**Comment by karateboy** [comment]
fixed in v 0.1.1212
