### ISSUE TITLE
[淹水感測] 淹水範圍模擬 實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#263]
![image](https://user-images.githubusercontent.com/28863560/80932136-af3e8900-8df0-11ea-9ca0-d729ed473d15.png)

**Comment by karateboy** [comment]
好了通知一下

**Comment by flyingapsara** [comment]
這是不是應該close了

**Comment by EideWang** [comment]
尚缺"未來6小時"
