### ISSUE TITLE
雨量預報圖片連結

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#27]
後方09_16_30_20為 hh_mm_ss_??

灰色模式預測未來1小時之時雨量
http://210.61.11.56/yunlinFlood/image/QpHeapImg/%E7%81%B0%E8%89%B2%E9%A0%90%E6%B8%AC/%E7%81%B0%E8%89%B2_1hr_fs.gif?09_16_30_20

灰色模式預測未來2小時之時雨量
http://210.61.11.56/yunlinFlood/image/QpHeapImg/%E7%81%B0%E8%89%B2%E9%A0%90%E6%B8%AC/%E7%81%B0%E8%89%B2_2hr_fs.gif?09_16_30_20

灰色模式預測未來3小時之時雨量
http://210.61.11.56/yunlinFlood/image/QpHeapImg/%E7%81%B0%E8%89%B2%E9%A0%90%E6%B8%AC/%E7%81%B0%E8%89%B2_3hr_fs.gif?09_16_30_20

灰色模式預測未來4小時之時雨量
http://210.61.11.56/yunlinFlood/image/QpHeapImg/%E7%81%B0%E8%89%B2%E9%A0%90%E6%B8%AC/%E7%81%B0%E8%89%B2_4hr_fs.gif?09_16_30_20

灰色模式預測未來5小時之時雨量
http://210.61.11.56/yunlinFlood/image/QpHeapImg/%E7%81%B0%E8%89%B2%E9%A0%90%E6%B8%AC/%E7%81%B0%E8%89%B2_5hr_fs.gif?09_16_30_20

灰色模式預測未來6小時之時雨量
http://210.61.11.56/yunlinFlood/image/QpHeapImg/%E7%81%B0%E8%89%B2%E9%A0%90%E6%B8%AC/%E7%81%B0%E8%89%B2_6hr_fs.gif?09_16_30_20

**Comment by karateboy** [comment]
fixed in v 0.1.1210
