### ISSUE TITLE
[單一入口網] 無法刪除使用者

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#271]
![image](https://user-images.githubusercontent.com/28863560/80936223-bcfd0a00-8e02-11ea-8109-c014e8dc1fb3.png)

**Comment by karateboy** [comment]
API 沒有刪除使用者?
因為剛剛查了一下API文件沒有

**Comment by Elvis0059** [comment]
這功能當初需求定義不明確，RD沒有做該工項，
後來不是在LINE討論說，有時間在做。
請Eide跟Kaka討論一下deadline吧

**Comment by EideWang** [comment]
@Elvis0059 因開發進度不斷delay，原本預計5/18開始能處理這些issue、5/31能全部解決，但沒有。
此為重要issue，非可有可無的優化功能，已經時間標記改至6/7

**Comment by karateboy** [comment]
0605
