### ISSUE TITLE
[淹水感測] 五河局、防災中心淹水感測器資料抓取錯誤；防災中心icon沒有正確套用

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#274]
![image](https://user-images.githubusercontent.com/28863560/81027273-b4164200-8eaf-11ea-92ec-2ddb884e0382.png)

目前防災中心的測站，詮釋資料抓不到，icon也沒有套用[淹(防災)]

**Comment by karateboy** [comment]
防災中心的資料會怎麼呈現? 權責單位?

**Comment by EideWang** [comment]
@karateboy 格式跟縣府、五河局的一樣
權責單位是"水利署防災中心"
物理量只有"淹水高度"

**Comment by karateboy** [comment]
@flyingapsara 水利署防災中心沒有對應的icon

**Comment by karateboy** [comment]
fixed 0506
