### ISSUE TITLE
[防汛工具] 抽水站 放大鏡 表格介接異常

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#277]
![image](https://user-images.githubusercontent.com/28863560/81027723-5c78d600-8eb1-11ea-9473-4d4d0df99ff1.png)

在系統管理-抽水站管理中，是有填數字的
![image](https://user-images.githubusercontent.com/28863560/81027743-6b5f8880-8eb1-11ea-8e5c-e349c7a6caad.png)

此外，放大鏡跟系統管理之間切換時，會導致表格卡在上一個的情況
例如由抽水站放大鏡切到抽水站管理，modal仍卡在放大鏡表格
![image](https://user-images.githubusercontent.com/28863560/81027817-b4afd800-8eb1-11ea-8a7f-581cf74c5379.png)

反之由系統管理切回放大鏡，表格會卡在系統管理
![image](https://user-images.githubusercontent.com/28863560/81027844-cbeec580-8eb1-11ea-8f97-3a93ef533d34.png)

**Comment by karateboy** [comment]
fixed 0505
