### ISSUE TITLE
[水位資訊] 林厝寮排水一highchart水位無法做圖、達警戒沒顯示在警戒table

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#282]
![image](https://user-images.githubusercontent.com/28863560/81130854-c958a280-8f7b-11ea-9643-340beb7a9c63.png)
![image](https://user-images.githubusercontent.com/28863560/81130872-d5446480-8f7b-11ea-92cf-fe0c10a7fdfb.png)

**Comment by Elvis0059** [comment]
![2020-05-11_155630](https://user-images.githubusercontent.com/57971834/81537647-1a173380-93a0-11ea-9cba-1d85c677269e.jpg)
溢堤警戒有該站

**Comment by Elvis0059** [comment]
![2020-05-11_155952](https://user-images.githubusercontent.com/57971834/81537900-7d08ca80-93a0-11ea-9f2f-39fc4eeb581a.jpg)
前24hr歷史資料也有

**Comment by karateboy** [comment]
fixed 0511
