### ISSUE TITLE
[歷史水位資料] 縣管水位站、中央管水位站 highchart作圖修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#283]
![image](https://user-images.githubusercontent.com/28863560/81132640-bcd74880-8f81-11ea-85a9-ed7822a47ee1.png)
警戒值不應出現在可點擊取消的選項中

另外，查詢後須設定default只展示"水位"，其餘選項乃使用者主動點擊後才展示作圖

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81133914-aaf7a480-8f85-11ea-9448-25dc60dcd6c3.png)

**Comment by EideWang** [comment]
@karateboy  實際使用時發現，假如把警戒值隱藏了(永遠作圖)，在只繪製電池電壓時，會發生有冗的警戒線在圖上...

有辦法把警戒線包在任一水位物理量(點擊任一水位物理量便會繪製警戒線)嗎?
若不能，就讓警戒線的checkbox維持現狀吧！

**Comment by karateboy** [comment]
電池電壓不在歷史水位資料...

**Comment by karateboy** [comment]
無法連動...

**Comment by karateboy** [comment]
fixed 0506
