### ISSUE TITLE
[歷史雨量預報] Highchart修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#284]
![image](https://user-images.githubusercontent.com/28863560/81134475-74bb2480-8f87-11ea-9099-07c8a7b5e7e8.png)

1~6小時預測雨量需以柱狀圖作圖
下方checkbox部分請按照123456順序排序展示
default僅展示"1小時預測雨量"

另，原先GUI SEPC沒有畫警戒線，這邊需補加，警戒線四條，同"歷史累積雨量"的

**Comment by EideWang** [comment]
另，補加的4條豪雨警戒線在checkbox部分也是隱藏

**Comment by karateboy** [comment]
@Elvis0059 雨量預報沒有警戒
