### ISSUE TITLE
[歷史累積雨量] highchart修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#287]
![image](https://user-images.githubusercontent.com/28863560/81135408-a41f6080-8f8a-11ea-978b-b8ecbb9c9f92.png)

累積10分鐘, 累積1小時, 累積3小時, 累積6小時, 累積12小時, 累積24小時需以柱狀圖作圖

default僅展示 "累積10分鐘"

豪雨的四個警戒在checkbox部分需隱藏

checkbox部分請依照 累積10分鐘, 累積1小時, 累積3小時, 累積6小時, 累積12小時, 累積24小時的順序排序展示

**Comment by karateboy** [comment]
@Elvis0059  請修改Measure.Name 和對應順序

**Comment by karateboy** [comment]
fixed 0508

**Comment by EideWang** [comment]
checkbox部分請依照 累積10分鐘, 累積1小時, 累積3小時, 累積6小時, 累積12小時, 累積24小時的順序排序展示

![image](https://user-images.githubusercontent.com/28863560/81516245-d73a6900-9369-11ea-86f1-ad8a2ec80ee5.png)
四條豪雨警戒 應以橫線作圖
目前柱狀圖作圖似乎有所有物理量全疊在同一條柱子上的問題(?)

**Comment by karateboy** [comment]
fixed 0520
