### ISSUE TITLE
[歷史資料-縣管水位站] 查詢單一測站 下方表格未實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#289]
表格呈現，欄位包含{即時水位(m)、預報時間點模擬水位(m)、未來1小時(m)、未來2小時(m)、未來3小時(m)、未來4小時(m)、未來5小時(m)、二級警戒(m)、一級警戒(m)、堤頂高(m)、資料時間}

**Comment by karateboy** [comment]
請修改對應Measure.Name

**Comment by karateboy** [comment]
fixed 0508
