### ISSUE TITLE
移動式抽水機監控系統 尚未嵌入頁面

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#29]
http://61.216.39.38:99/Default.aspx

**Comment by karateboy** [comment]
這個早就做了, 主因是網頁是https, 但連結是http, 瀏覽器會阻擋這類混用的連結.
![image](https://user-images.githubusercontent.com/1067042/70515521-6c91c100-1b70-11ea-987d-3c088fb1db2d.png)

**Comment by karateboy** [comment]
若要解決, 可以手動設定允許這種情況.
![image](https://user-images.githubusercontent.com/1067042/70515716-bed2e200-1b70-11ea-88db-e871c9bcae88.png)

**Comment by karateboy** [comment]
點擊允許不安全的指令碼
![image](https://user-images.githubusercontent.com/1067042/70515804-e9bd3600-1b70-11ea-93e1-8907355e2a48.png)

**Comment by karateboy** [comment]
之後回到原本網站起點, 就ok了
![image](https://user-images.githubusercontent.com/1067042/70515870-078a9b00-1b71-11ea-99cf-27cf45c71dc8.png)

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/70673959-5e9e8600-1cbf-11ea-9839-257e46428478.png)
載入後會變成404

**Comment by karateboy** [comment]
這需要server 設定redirect. github page無法提供. 
Workaround是回到原本的網址, 就會正確

**Comment by EideWang** [comment]
無法處理的話就改成開啟新分頁，感謝!

**Comment by karateboy** [comment]
Fixed in v. 0.1.1212
