### ISSUE TITLE
[歷史淹水感測資料] highchart修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#292]
![image](https://user-images.githubusercontent.com/28863560/81141961-c623dd80-8fa0-11ea-9ff0-74cb1ba9013b.png)

同水位站議題討論，不知警戒值是否能和"淹水高度"綁一起，隱藏checkbox，跟淹水高度同進同消?

另，告知、通知、告警  文字須更新為"預警、警戒、危險"

**Comment by karateboy** [comment]
@Zunnex highchart的警報名稱是API提供.
@Elvis0059 AlertLevels.Level.Name

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81142267-c1135e00-8fa1-11ea-8fd2-facc5fed6cf4.png)
圖表title請更改為"鄉鎮市"+" "+"測站名稱"，例如 臺西鄉 溪頂村_村落2

雨量站、各水位站的圖表TITLE也麻煩依這個命名規則作修改，感謝

**Comment by karateboy** [comment]
fixed 0508

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81516627-17e6b200-936b-11ea-9248-f2b0750ed320.png)
紅圈部分仍未修正

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81518026-54b4a800-936f-11ea-8a14-83cf34e4daef.png)
1. 圖上"電池電壓"展示到小數點後兩位
2. 淹水高度(cm) -->淹水深度(cm)

**Comment by Elvis0059** [comment]
該issue是要API改警報名稱嗎?

**Comment by karateboy** [comment]
@Elvis0059 是的

**Comment by Elvis0059** [comment]
已更新為"預警、警戒、危險"。

**Comment by karateboy** [comment]
fixed 0525

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82852734-4f8e5600-9f36-11ea-8a78-63902828d9c4.png)
@karateboy 電池電壓僅需展示到小數點後2位，這個沒有改到

**Comment by karateboy** [comment]
fixed 0527
