### ISSUE TITLE
[歷史淹水感測資料] 查詢單一測站 下方表格未實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#293]
欄位：淹水高度(cm)、反應(cm)、預警(cm)、警戒(cm)、危險(cm)、電池電壓(V)、訊號強度(dBm)、資料時間

**Comment by karateboy** [comment]
@Elvis0059 請修改歷史資料Measure.Name, AlertLevels.Name

**Comment by karateboy** [comment]
fixed 0508
