### ISSUE TITLE
[歷史決策建議分析報告] 缺少"上傳日期"

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#294]
![image](https://user-images.githubusercontent.com/28863560/81143334-35e79780-8fa4-11ea-9225-20a5c4331ee2.png)

GUI SPEC有報告的"上傳日期"，目前缺少此欄位

另，報告下載的icon麻煩C哥置中，謝謝

**Comment by karateboy** [comment]
@Elvis0059 麻煩API 提供上船日期

**Comment by karateboy** [comment]
fixed 0511
