### ISSUE TITLE
[水位infobox] 中央管水位站、潮位站infobox展示項目修改

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#295]
以原訂業主須展示的內容來看，

中央管水位站包含：{流域編號、經緯度、高程、即時水位、一級警戒、二級警戒、三級警戒、堤頂高、狀態、所屬流域、河川/溪流、地址、權責單位、資料時間}

潮位站包含：{站碼、經緯度、高程、即時潮位、位置描述、權責單位、資料時間}

目前仍以共用原先縣管水位站的modal模板內容展示

中央管水位站可沿用縣管水位站的藍色框框重點資訊部分(電池電壓空著)，其他項目則依上述欄位更新調整

潮位站則移除重點呈現部分，條列各欄位資料

**Comment by karateboy** [comment]
fixed 0511
