### ISSUE TITLE
[優化] 歷史淹水感測highchart展示修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#298]
![image](https://user-images.githubusercontent.com/28863560/81252126-aa2f4300-9057-11ea-9bd4-6d1bcbe16a14.png)

如圖，Y軸目前為"淹水高度"，即使切換成只有訊號強度，仍然顯示"淹水高度"，造成圖表判讀理解錯誤
![image](https://user-images.githubusercontent.com/28863560/81252200-e06cc280-9057-11ea-8de8-ab6b16f9351e.png)

highchart有辦法依照勾選之物理量設定對應的Y軸標題嗎? 或是C哥有建議怎麼解決使用者判讀圖表的問題嗎?

**Comment by karateboy** [comment]
可以  但是API要告知測項是哪一個座標軸.  API同時也要提供座標軸的資訊
