### ISSUE TITLE
[單一入口網] 資料修改功能缺失

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#299]
![image](https://user-images.githubusercontent.com/28863560/81360955-a6f78e00-910f-11ea-80c1-a67338b24761.png)

1. 使用者名稱不應可以被修改
2. 假如未填入變更密碼，就沒辦法編輯其他欄位然後更新
3. 使用者不能自己決定自己可不可以成為管理者(目前測試，非管理者帳號可以把自己變成管理者)
4. 頭像圖檔位置，顯示當前圖片檔名

**Comment by EideWang** [comment]
目前測試，一旦改成"管理者"，就無法取消改回非管理者狀態

**Comment by EideWang** [comment]
@karateboy 改不回非管理者的這個BUG有點嚴重，因為guest帳號有對外提供，怕警戒數值被亂動

**Comment by karateboy** [comment]
@Elvis0059 改不回非管理者  應該是API後台過濾掉的吧?

**Comment by EideWang** [comment]
頭像上傳更新失敗

**Comment by EideWang** [comment]
預設填入特殊字串， @Elvis0059 提供定義
讓C哥將這個字串當作不變動密碼

**Comment by Elvis0059** [comment]
使用者無法從管理者改為非管理者，API修正了。

至於密碼修改，該欄位在API不是必要的，有傳密碼跟確認密碼字串給API才會改，
因此，需要密碼才能存，應是前端自己檢核的部分，請C哥確認。

**Comment by karateboy** [comment]
fixed 0605

**Comment by EideWang** [comment]
@karateboy  
![image](https://user-images.githubusercontent.com/28863560/84103598-1bdb2200-aa46-11ea-8aa1-c524405b8130.png)

**Comment by karateboy** [comment]
fixed 0609
