### ISSUE TITLE
[淹水量體分析] UI調整、假資料清空

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#302]
![image](https://user-images.githubusercontent.com/28863560/81376057-56932700-9135-11ea-9913-c618341a26aa.png)

決策系統整體規劃上，是會全版蓋住地圖的，所以要靠視窗中的MAP大小撐開modal
MAP跟右側選項表格區以50-50比例呈現(移動式抽水機智慧調度也是同樣設計概念)

**Comment by EideWang** [comment]
之後介接實際資料時，右方表格可能會很多列向下展開，此時的scroll bar不是拉全部畫面，而是只拉右下方(不含勾選控制區)表格區。
不知此設計規劃是否有實作上的問題呢?

**Comment by karateboy** [comment]
fixed 0508
