### ISSUE TITLE
[UI修正] 雨量警戒

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#303]
![image](https://user-images.githubusercontent.com/28863560/81394991-6d497600-9155-11ea-92dd-ce805e9cabeb.png)
豪雨特報通知紀錄  修正如上，表格column兩個需互調，coulmn title文字修改
紅圈部分的list為{查詢全部/超大豪雨特報/大豪雨特報/豪雨特報/大雨特報} (我忘記"大雨特報"後來是怎處理警戒判定了，有API?)

![image](https://user-images.githubusercontent.com/28863560/81394943-5c990000-9155-11ea-9b0b-59486cc9300d.png)
淹水警戒通知紀錄 修正如上，表格column兩個需互調，coulmn title文字修改
紅圈部分list為{查詢全部/一級警戒/二級警戒}

**Comment by EideWang** [comment]
尚未正確修正

**Comment by karateboy** [comment]
@Elvis0059 剩下修改 查詢警戒名稱

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82852569-e0186680-9f35-11ea-8d78-2720f7785904.png)
@karateboy 淹水警戒通知紀錄的column順序尚未調整

**Comment by karateboy** [comment]
fixed 0527

**Comment by Elvis0059** [comment]
這個要API改豪雨警戒的名稱嗎?
加上特報2個字??

**Comment by EideWang** [comment]
@Elvis0059 是的，麻煩你

**Comment by Elvis0059** [comment]
豪雨特報警戒名稱已調整，請確認。
