### ISSUE TITLE
[UI優化] 單一入口網

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#305]
![image](https://user-images.githubusercontent.com/28863560/81396537-2ad56880-9158-11ea-837f-b5574ecfb903.png)

![image](https://user-images.githubusercontent.com/28863560/81396778-9c151b80-9158-11ea-9f24-f4eee7f95246.png)

![image](https://user-images.githubusercontent.com/28863560/81397368-be5b6900-9159-11ea-87f0-238025968eac.png)

**Comment by karateboy** [comment]
fixed 0510

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81515390-66458200-9366-11ea-9c83-a3c1f6266d95.png)

這部分有點突兀，再調整，感謝！

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81515434-a7d62d00-9366-11ea-93b4-b7bf49a65098.png)

1. 雲林縣政府水利處那段title文字仍未垂直置中
2. 紅圈處破版調整

**Comment by karateboy** [comment]
fixed 0512

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81772237-f2e37200-9517-11ea-8c5b-c9a04c4f29e1.png)

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/83367451-2878ce00-a3e7-11ea-970e-304ca7268a04.png)

我看還是一樣沒有改(?)
圖片一樣變形

**Comment by karateboy** [comment]
0610

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84490991-7db1bb00-acd6-11ea-9ab9-5e53b0b3c88b.png)

登出紐未置中對齊

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84843939-d63cdb80-b07b-11ea-9718-15cab5b62ccf.png)
跑上去了

**Comment by karateboy** [comment]
那個是網站快取, refresh或用無痕就會正常了

**Comment by EideWang** [comment]
清除快取、無痕，都一樣，請再確認程式碼

**Comment by karateboy** [comment]
Chrome無痕 ok
Edge ok
程式真的沒問題

**Comment by karateboy** [comment]
@Zunnex 有問題的話, refresh是不是就解決?

**Comment by karateboy** [comment]
若refresh可以解決, 證明是瀏覽器cache

**Comment by EideWang** [comment]
我refresh跟無痕都試過，還是一樣的結果

**Comment by karateboy** [comment]
ylhg是因為游景年文字太短, 沒有換行
強制換行後已經正常
