### ISSUE TITLE
[UI修正] 水位警報通知紀錄

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#306]
![image](https://user-images.githubusercontent.com/28863560/81397745-8143a680-915a-11ea-9ed8-a2cd51a740f5.png)
紅圈部分的list{查詢全部/溢堤警戒/一級警戒/二級警戒/資料異常} 

下方表格應修正為
![image](https://user-images.githubusercontent.com/28863560/81397971-f020ff80-915a-11ea-8dee-1c232af7d191.png)

**Comment by karateboy** [comment]
警報選項名稱由API提供, 表格已修改

**Comment by Elvis0059** [comment]
歷史警戒紀錄無提供資料異常。
