### ISSUE TITLE
[UI修正] 路面淹水警戒通知紀錄

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#307]
![image](https://user-images.githubusercontent.com/28863560/81398261-79d0cd00-915b-11ea-825e-03325d45a180.png)

紅圈List{查詢全部/危險(淹水深度>30cm)/警戒(淹水深度>25cm)/預警(淹水深度>15cm)/反應(淹水深度>5cm)/資料異常}

**Comment by karateboy** [comment]
@Zunnex 該字串由API提供

**Comment by Elvis0059** [comment]
危險(淹水深度>30cm)/警戒(淹水深度>25cm)/預警(淹水深度>15cm)，API已調整。
反應(淹水深度>5cm)，歷史警戒無法提供。
