### ISSUE TITLE
[UI修正] 淹水感測infobox內容修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#308]
![image](https://user-images.githubusercontent.com/28863560/81517747-7bbeaa00-936e-11ea-885d-e56645aff23f.png)

1. 抱歉當初在寫spec時，淹水高度、淹水深度沒有統一，全平台應統一使用水利署規定之"淹水深度"
2. 電池電壓圖上需至小數點後兩位
3. 目前展示電池電壓或訊號強度時，淹水深度的警戒值都會展示，不應該這樣(很突兀)

**Comment by karateboy** [comment]
fixed 0511

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81632041-dffb6f80-943b-11ea-951b-79896d29e924.png)

1. 不好意思沒打清楚，請把"歷史"去掉
2. 訊號強度展示上無小數位數，如-74dBm
3. 電池電壓展示上雖有小數點後兩位，但似乎被強制轉為整數型，需修正，如14.56V
4. 淹水深度展示上目前設定為小數點後兩位，需修正微指到小數點後一位，如12.3cm

**Comment by karateboy** [comment]
fixed 0512
