### ISSUE TITLE
[歷史水位資料] 展示優化

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#309]
(一)縣管水位站
![image](https://user-images.githubusercontent.com/28863560/81518239-f6d49000-936f-11ea-8ef7-618aa08b63dc.png)

1. 選單需排序
2. 水位展示至小數點後兩位(查詢全部測站&查詢單一測站均要修改)
3. 電池電壓展示至小數點後兩位(查詢全部測站&查詢單一測站均要修改)
![image](https://user-images.githubusercontent.com/28863560/81518281-271c2e80-9370-11ea-8ddc-56448eb132e7.png)
4. checkbox依順序排列，水位, 電池電壓, 預報時間點模擬水位, 未來1小時水位, 未來2小時水位, 未來3小時水位, 未來4小時水位, 未來5小時水位, 二級警戒, 一級警戒, 堤頂高  (查詢全部測站&查詢單一測站均要修改)

(二)中央管水位站
![image](https://user-images.githubusercontent.com/28863560/81518690-731ba300-9371-11ea-8815-f434a0d92c2e.png)
1. 水位展示至小數點後兩位(查詢全部測站&查詢單一測站均要修改)
2. checkbox依順序排列，水位, 預報時間點模擬水位, 未來1小時水位, 未來2小時水位, 未來3小時水位, 未來4小時水位, 未來5小時水位, 三級警戒, 二級警戒, 一級警戒, 堤頂高  (查詢全部測站&查詢單一測站均要修改)

(三)潮位站
![image](https://user-images.githubusercontent.com/28863560/81518753-a78f5f00-9371-11ea-9894-345ba960cca9.png)
1. 潮高展示至小數點後兩位(查詢全部測站&查詢單一測站均要修改)

**Comment by karateboy** [comment]
fixed
