### ISSUE TITLE
請確認雨量、水位、淹水感測器、CCTV等infobox欄位內容項目

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#31]
從分享文檔摘錄整理於此，再麻煩C哥確認一下格式，( )內文字不要顯示

雨量站infobox：站名、站碼、經緯度、行政區、過去累積10min、1hr、3hr、6hr、12hr、24hr數值、權責單位、資料時間。

水位站infobox：站名、站碼、經緯度、行政區、高程、觀測原理、監測頻率、即時水位、二級警戒值、一級警戒值、堤頂高、狀況(指是否正常或達警戒狀況)、所屬水系、權責單位、資料時間。

淹水感測器infobox：站名、站碼、經緯度、行政區、高程、淹水高度、權責單位、資料時間。

CCTV infobox：站名、經緯度、行政區、狀態(指正常或斷線)、權責單位、資料時間、即時監控影像(2x2顯示，串接影像)。

**Comment by karateboy** [comment]
經緯度 再確認需要顯示嗎? 
因為已經畫在地圖上了

**Comment by EideWang** [comment]
需要呈現經緯度數值

**Comment by karateboy** [comment]
CCTV infobox：狀態(指正常或斷線) => API 沒有提供

**Comment by karateboy** [comment]
除CCTV state外, 都已經提供
