### ISSUE TITLE
[水位infobox]highchart展示修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#311]
![image](https://user-images.githubusercontent.com/28863560/81631540-a1b18080-943a-11ea-84ac-e76ae5aef105.png)

1. 紅圈處請齊頭
2. 縣管、中央管、潮位站的highchart作圖，目前雖有設定小數後兩位，但程式似乎強制轉成"整數"類型，麻煩C哥修正BUG

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81632401-b5f67d00-943c-11ea-8e6c-133a54c298c0.png)

縣管水位站infobox，水位跟電池電壓請互換checkbox順序，水位均統一以藍色畫線

**Comment by karateboy** [comment]
fixed 0512

**Comment by EideWang** [comment]
@karateboy C哥，水位站"縣管水位站infobox，水位跟電池電壓請互換checkbox順序，水位均統一以藍色畫線"這個沒有改到，再麻煩一下，感謝

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/81760102-f61b3580-94f8-11ea-9357-670bc63c89a2.png)

**Comment by karateboy** [comment]
race condition 
fixed 0513

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82630595-b6a1c700-9c25-11ea-9bf2-fb90dd98ca08.png)

目前文字換行齊頭的作法不恰當

**Comment by karateboy** [comment]
@Zunnex  要不然要怎麼改? 我覺得的還蠻好的

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82965966-410a7200-9ffc-11ea-87f6-c3237d1098a2.png)

**Comment by karateboy** [comment]
fixed 0527
