### ISSUE TITLE
[UI優化] 優化建議

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#313]
![image](https://user-images.githubusercontent.com/28863560/81660447-595f8600-946d-11ea-9cca-1cdbeba19490.png)
1. 統一加入九個主選項跟下面子選項之間這個10px高的div

![image](https://user-images.githubusercontent.com/28863560/81668352-24583100-9477-11ea-9233-719fe823e4ea.png)
2. 讓button有立體感(我試著取消紅色箭頭這個項目)

![image](https://user-images.githubusercontent.com/28863560/81668223-f2df6580-9476-11ea-9180-fdaa47b3e6e8.png)
3. 配色調整
全站原先的黑色字，以深藍黑取代 #192E5B
主選項button、modal title區塊，#1D65A6，hover/clicked #277CC8
子選項button，#72A2C0 ，hover/clicked #4792c0
主控板底色，#454552

![image](https://user-images.githubusercontent.com/28863560/81669205-78174a00-9478-11ea-9ca5-561372c69a69.png)
4. title文字移除高度限制，使用align-items: center;
5. title背景的上下padding改成0.25rem

**Comment by EideWang** [comment]
@karateboy 請查看google drive配色文檔做修正，謝謝
https://drive.google.com/drive/u/0/folders/1tZYVEGdkdsddEvX6Ue7qDMZ81GERRxBt

**Comment by karateboy** [comment]
fixed 0514

**Comment by EideWang** [comment]
@karateboy 警戒icon跟table 文字部分尚未更改

**Comment by karateboy** [comment]
@Zunnex 建議先把這個關掉...新開1或多個issue指出哪一項沒改. 這樣比較容易追蹤哪一個沒改到. 謝謝
