### ISSUE TITLE
[UI優化] icon更換

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#314]
https://drive.google.com/drive/u/0/folders/1QI67IgYiV3sZvrgRGIJtuisDd-oIf6S9
3個icon更換，檔案SVG已上傳至google drive icon資料夾中

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/83035681-55865300-a06c-11ea-849a-57fce5b77146.png)
鋸齒狀

**Comment by EideWang** [comment]
已更新提高解析度，google預覽才會鋸齒

**Comment by karateboy** [comment]
已經移除 雨量預報/累積雨量下載icon

**Comment by EideWang** [comment]
C哥，防汛工具放大鏡 和 溪流大排放大鏡 沒有改到

**Comment by karateboy** [comment]
fixed 0606

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84102324-bf2a3800-aa42-11ea-90fc-193263b336c2.png)

其他都沒換到

另，麻煩移除icon border，水位站溪流大排那邊的也是，移除border
移除後應如下
![image](https://user-images.githubusercontent.com/28863560/84102394-ec76e600-aa42-11ea-9667-cf3d8758c75d.png)

**Comment by karateboy** [comment]
fixed 0609
