### ISSUE TITLE
[天氣概況] 颱風資訊、颱風路徑圖 無資料

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#316]
![image](https://user-images.githubusercontent.com/28863560/81778440-75266300-9525-11ea-8e05-541464dc6103.png)

目前氣象局有發布颱風相關資訊，但我們的網頁上API看來沒有接到資料
![image](https://user-images.githubusercontent.com/28863560/81778521-9ab36c80-9525-11ea-995e-eeb044c79f51.png)

**Comment by karateboy** [comment]
今天有颱風了!
