### ISSUE TITLE
[水位infobox] 之前新接的7座水位站highchart的水位畫不出來

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#317]
![image](https://user-images.githubusercontent.com/28863560/81782681-c2f29980-952c-11ea-9e05-672320cb2127.png)
![image](https://user-images.githubusercontent.com/28863560/81782702-cab23e00-952c-11ea-9620-9c43d8a2c79d.png)

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/83252446-cef18300-a1dd-11ea-91c4-860bf379e0cb.png)
電壓是正常的

**Comment by karateboy** [comment]
之前畫不出來是因為 堤頂高是NaN
