### ISSUE TITLE
[系統管理] 自主防災社區管理 編輯聯絡資訊失敗

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#318]
![image](https://user-images.githubusercontent.com/28863560/81783815-8031c100-952e-11ea-9dc0-4e20e8389889.png)

測試編輯其中一欄，發現infobox和統計表(放大鏡)都沒有連動變更
![image](https://user-images.githubusercontent.com/28863560/81783919-ab1c1500-952e-11ea-8bb6-50d441106917.png)
![image](https://user-images.githubusercontent.com/28863560/81783890-9f305300-952e-11ea-953e-d04933ed132f.png)

**Comment by karateboy** [comment]
fixed 0513
