### ISSUE TITLE
[防汛工具] 抽水站infobox 缺少"站號"

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#319]
![image](https://user-images.githubusercontent.com/28863560/81786064-c50b2700-9531-11ea-951e-033716eea74b.png)

詮釋資料遺漏"站號"

**Comment by EideWang** [comment]
infobox欄位：站號、經緯度、村里、設計抽水量(CMS)、總抽水量、進水、出水、引水設施、主油槽、日用油槽、現場環境、動力電源、備用電源、建置年份、**權責單位**、保護村落

註：跟其它感測站統一把"管理單位"稱作"權責單位"

**Comment by karateboy** [comment]
fixed 0513
