### ISSUE TITLE
[重要]防汛工具>抽水站、水閘門、移動式抽水機表格視窗調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#32]
目前因表格資訊過於龐大，觀看上不容易看懂
看C哥是否能調整字體大小或彈出視窗大小來讓內容容易閱讀一些，感謝!

**Comment by karateboy** [comment]
fixed in final release

**Comment by EideWang** [comment]
抽水站、水閘門仍舊難以閱讀

**Comment by karateboy** [comment]
欄位過多, 列數過多  就一定會有scroll bar.  要好閱讀, 請幫忙刪除不必要的欄位

**Comment by EideWang** [comment]
有scroll bar沒關係，因為欄位內容目前依業主要求無法刪減..
