### ISSUE TITLE
[防汛工具] 水閘門infobox 展示修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#320]
![image](https://user-images.githubusercontent.com/28863560/81787575-d6edc980-9533-11ea-8206-44603cfc1c5b.png)

水閘門infobox title應呈現為下崙大排一 右岸1號水門
"所屬流域"+" "+"水門名稱"

------------
空資料請以雙減號替代

**Comment by EideWang** [comment]
infobox欄位請以下列順序排列展示：編號、行政區、經緯度、堤內閘門數、堤內閘門操作機制、堤外閘門數、堤內閘門操作機制、**權責單位**、建置年份

註：跟其它感測站統一把"管理單位"稱作"權責單位"

**Comment by karateboy** [comment]
@Elvis0059 空資料請用"--"

**Comment by Elvis0059** [comment]
什麼欄位的空資料用"--"??

**Comment by karateboy** [comment]
@Zunnex 那些空資料用--

**Comment by karateboy** [comment]
fixed 0525
