### ISSUE TITLE
[防汛工具] 防潮閘門infobox 資料缺漏、展示修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#321]
![image](https://user-images.githubusercontent.com/28863560/81788253-d570d100-9534-11ea-9210-1a7bdde8af45.png)

1. infobox欄位請依下列順序展示：編號、經緯度、所屬流域、堤內閘門數、堤內閘門操作機制、堤外閘門數、堤外閘門操作機制、閘泵能量(CMS)、閘泵數、建置年份

2. 堤外閘門數、堤外閘門操作機制 這兩項目前看沒接上API資料(?)

**Comment by karateboy** [comment]
fixed

**Comment by EideWang** [comment]
@karateboy 
堤外閘門數、堤外閘門操作機制 這兩項目前看沒接上API資料

**Comment by karateboy** [comment]
API拼錯字, fixed 0520
