### ISSUE TITLE
[防汛工具] 移動式抽水機infobox 修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#322]
![image](https://user-images.githubusercontent.com/28863560/81790189-9f811c00-9537-11ea-895e-6d3d8e081a55.png)

1. infobox title為"組織"+" "+"抽水機編號"，如：二崙鄉公所 二崙-M001
2. infobox欄位請依下列排序展示：經緯度、口徑大小(英吋)、**抽水量(CMS)**、電力、網路通訊、監測功能、保管人員、保管人員聯絡方式、存放位置、備註

**Comment by karateboy** [comment]
fixed 0513
