### ISSUE TITLE
[防汛工具] 移動式抽水機 統計表格(放大鏡) 總數 有問題

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#324]
![image](https://user-images.githubusercontent.com/28863560/81794413-5338da80-953d-11ea-941d-81f09b9a1fa0.png)
 目前被固定為0，沒有隨著前四欄數字增加而加總

另，除了備註欄的描述外，其餘均需水平置中(Title如抽水機台數、已出動台數、剩下可出動台數(待命)、故障台數也需水平置中)

**Comment by karateboy** [comment]
fixed 0513
