### ISSUE TITLE
[UI優化] Highchart展示統一

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#334]
業主舉例表示，淹水感測器有的圖上的線的測項有點，有的沒點，要求統一

**Comment by karateboy** [comment]
那個是highchart自動偵測  畫面太窄就不畫點  比較寬資料又比較少 就沒有點

**Comment by EideWang** [comment]
@karateboy 須設定enabled: false
![image](https://user-images.githubusercontent.com/28863560/82296203-6d623500-99e3-11ea-9855-2a98e108728e.png)

Example
http://jsfiddle.net/aeZ6P/
