### ISSUE TITLE
[天氣概況] 應變小組開設API介接無法正常顯示

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#336]
![image](https://user-images.githubusercontent.com/28863560/82124635-f9514280-97d2-11ea-923b-f37a729592a8.png)
API來源有新增黃蜂颱風開設資訊，但平台上仍是無開設狀態

**Comment by EideWang** [comment]
@karateboy  討論後決定此issue的處理方法，僅須將title"水利署災害應變小組"
修改成"災害應變小組開設建議"
API source不變

**Comment by karateboy** [comment]
fixed 0521

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82622777-2f4a5880-9c11-11ea-878f-7038f313cfeb.png)

@karateboy 不知道顯示"未達開設標準"這個是否是API有出呢?

**Comment by karateboy** [comment]
@Zunnex 有API, 但API吐空字串
