### ISSUE TITLE
[雨量警戒] 鄉鎮市淹水警戒 表格完全無資訊、地圖無顯示

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#338]
![image](https://user-images.githubusercontent.com/28863560/82274413-af26b780-99b2-11ea-8cee-dcc54d601d1e.png)

![image](https://user-images.githubusercontent.com/28863560/82274468-cebde000-99b2-11ea-9ef2-1a111161079c.png)

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/82320659-39e4d200-9a06-11ea-995c-f0b047f4206f.png)

**Comment by karateboy** [comment]
fixed 0519

**Comment by EideWang** [comment]
現在無法檢驗確認，暫時保留此issue
