### ISSUE TITLE
[雨量警戒] 豪雨特報通知紀錄 未實作

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#342]
![image](https://user-images.githubusercontent.com/28863560/82275343-16de0200-99b5-11ea-9af7-93a49f9138e9.png)
多站觸發特報，卻查無紀錄

**Comment by Elvis0059** [comment]
請Eide將senslink上豪雨警戒改回原先介接的物理量，而非豪雨特報警戒發布群的警戒。
