### ISSUE TITLE
[淹水量體分析] 時間點一直卡在5/18 11:00未更新

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#345]
![image](https://user-images.githubusercontent.com/28863560/82276455-e8adf180-99b7-11ea-81e0-59b55a951e45.png)

**Comment by karateboy** [comment]
API回報的最新資料就在這個時間點.

**Comment by EideWang** [comment]
已確認國網中心主機故障維修中，後續觀察主機修復狀況後，再關閉此issue

**Comment by karateboy** [comment]
目前為無資料
