### ISSUE TITLE
[水位infobox] 中央管水位站 清水溪橋 警戒值錯誤、歷線圖無法顯示

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#347]
![image](https://user-images.githubusercontent.com/28863560/82319173-b2965f00-9a03-11ea-989b-85e1c76687b3.png)

**Comment by karateboy** [comment]
@flyingapsara 麻煩檢查

**Comment by karateboy** [comment]
這同樣是堤頂高NaN所致...已經修正

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/83367595-f025bf80-a3e7-11ea-9fc7-1f724a70fc39.png)
still wrong

**Comment by karateboy** [comment]
fixed
