### ISSUE TITLE
單一入口網>內容調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#35]
![image](https://user-images.githubusercontent.com/28863560/70769359-23c24e00-1da4-11ea-8fab-bd9dea92f277.png)

智慧防汛整合平台：以新網址串接
雲端水情圖資整合平台：http://210.61.11.57/yunlinWRD3/gee/user/index.php?
請移除雲端水位資訊那個項目

**Comment by karateboy** [comment]
fixed in final release
