### ISSUE TITLE
[防汛備料] 統計總表(放大鏡) 合計欄計算有問題

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#350]
![image](https://user-images.githubusercontent.com/28863560/82398102-9686d200-9a84-11ea-9000-efa7331d4f40.png)

**Comment by karateboy** [comment]
API提供一個測站叫"合計"  資料卻不會因此更新

**Comment by karateboy** [comment]
API fixed

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82513077-83d3d200-9b44-11ea-97cb-71f37cf214fe.png)
 Still wrong

**Comment by karateboy** [comment]
@Elvis0059 奇怪昨天看不是修好了?

**Comment by Elvis0059** [comment]
可以儲存呀，怎樣有問題?
是要自動合計? 還是無法存?

**Comment by karateboy** [comment]
@Elvis0059 會自動合計嗎? 不會的話就要靠我額外更新

**Comment by karateboy** [comment]
fixed 0525
