### ISSUE TITLE
[防汛備料] EXCEL下載下來的表格與平台上的表格資料內容不一致

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#351]
![image](https://user-images.githubusercontent.com/28863560/82398503-96d39d00-9a85-11ea-8b38-bbf1ddf2ab20.png)
![image](https://user-images.githubusercontent.com/28863560/82398523-9fc46e80-9a85-11ea-8f2a-e84d93402603.png)

統計表格有內容，但下載下來的EXCEL卻是空的

**Comment by karateboy** [comment]
fixed 0520
