### ISSUE TITLE
[UI優化] 相關連結管理 文字修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#356]
![image](https://user-images.githubusercontent.com/28863560/82413407-dca15d00-9aa7-11ea-9647-99e673dd8100.png)

依原先規劃調整文字

**Comment by karateboy** [comment]
不了解這要修改啥

**Comment by EideWang** [comment]
抱歉我複製貼上貼錯圖
![image](https://user-images.githubusercontent.com/28863560/82621287-4b4bfb00-9c0d-11ea-9979-224c6d6326cd.png)

文字修正

**Comment by karateboy** [comment]
fixed
