### ISSUE TITLE
[UI優化] 圖層&地址搜尋

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#358]
![image](https://user-images.githubusercontent.com/28863560/82416416-969ac800-9aac-11ea-848d-77f823d236fe.png)

**Comment by karateboy** [comment]
bootstrap 文字效果無法取消 fixed 0521

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82621503-dc22d680-9c0d-11ea-8096-ddbd150ba823.png)

**Comment by karateboy** [comment]
fixed 0523
