### ISSUE TITLE
[UI優化] 系統管理選單

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#359]
![image](https://user-images.githubusercontent.com/28863560/82418176-3e18fa00-9aaf-11ea-9919-d1d9286ba33f.png)

**Comment by karateboy** [comment]
fixed 0521

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82512448-c09ec980-9b42-11ea-9daa-07e5453b7017.png)
@karateboy  C哥，字需要是白色的(登出&下方的button都是)，再麻煩一下，謝謝

**Comment by karateboy** [comment]
fixed 0521
