### ISSUE TITLE
[普通]單一info box呈現

### ISSUE THREAD

**Issue by PerryWu** [karateboy/ylfs_demo#36]
![image](https://user-images.githubusercontent.com/11898742/70856721-aa01a000-1f1c-11ea-85fc-bc74891f3344.png)

這info box太多了，畫面非常亂

**Comment by karateboy** [comment]
從樹枝點選, 會把先前的InfoBox關掉. 但若使用者自己點的, 不會關掉.

**Comment by EideWang** [comment]
自己點的infobox，在點擊其他地方時須關閉

**Comment by karateboy** [comment]
fixed in v0.1.1226_1
改用modal
