### ISSUE TITLE
[UI優化] 雨量警戒-鄉鎮市淹水警戒

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#362]
![image](https://user-images.githubusercontent.com/28863560/82426246-314dd380-9aba-11ea-8e9a-08394c93aa7d.png)

**Comment by karateboy** [comment]
fixed 0521

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82637978-7a2b9680-9c38-11ea-9318-edcfc196bc29.png)

@karateboy C哥抱歉，我沒注意到欄位寬度與淹水警戒不同，因此要再麻煩你改回原先排板方式(比較好看)，不好意思！

**Comment by karateboy** [comment]
fixed

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82769725-5babe200-9e68-11ea-936a-976158421805.png)

@karateboy 
紅圈處目前看font-weight是設500，應改為700(bold)

**Comment by karateboy** [comment]
fixed 0525
