### ISSUE TITLE
[UI優化] 雨量警戒-鄉鎮市豪雨特報

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#363]
![image](https://user-images.githubusercontent.com/28863560/82426896-ff893c80-9aba-11ea-9029-7fbe04cc35f7.png)

**Comment by karateboy** [comment]
fixed 0521

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82801751-625e4780-9eb0-11ea-83f8-f4e1d0952e6d.png)
色碼錯誤
應改為#ea714b

**Comment by karateboy** [comment]
fixed 0525

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82851428-616dfa00-9f32-11ea-91df-d9c82770d821.png)

**Comment by karateboy** [comment]
fixed 0527
