### ISSUE TITLE
reload 頁面，會404

### ISSUE THREAD

**Issue by PerryWu** [karateboy/ylfs_demo#37]
一旦Path 不是https://yliflood.yunlin.gov.tw/Portal2/
reload 一定變成 404

![image](https://user-images.githubusercontent.com/11898742/70856734-f4831c80-1f1c-11ea-8ae7-0780e38474f8.png)

**Comment by karateboy** [comment]
這是因為預設是使用HTML5 history mode.
這需要額外設定IIS server.

為了快速修正, 將改用hash mode

**Comment by karateboy** [comment]
已經改用hash mode
