### ISSUE TITLE
[淹水潛勢圖] 級距&色碼

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#372]
![image](https://user-images.githubusercontent.com/28863560/82516690-01501000-9b4e-11ea-825b-36b230c64fba.png)

註：水規所沒有0.15m-0.3m，但我們須補加此一層級
0.15m-0.3m #ffeecd
0.3m-0.5m #ffd380
0.5m-1m #fcba09
1m-2m #ff620b
2m-3m #fb1717
　>3m #850001

**Comment by Elvis0059** [comment]
淹水範圍模擬API已上，已套用該色階。
