### ISSUE TITLE
[自主防災社區管理] 刪除功能失效

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#374]
![image](https://user-images.githubusercontent.com/28863560/82621154-d973b180-9c0c-11ea-9c14-297967463e54.png)

欲刪除兩個測試站點，卻發現無法使用刪除

**Comment by karateboy** [comment]
我順利刪除了...功能是好的

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/82623620-2c506780-9c13-11ea-8bf5-c88ed21906db.png)
刪除要出現勾勾...選定才能刪除

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82769924-35d30d00-9e69-11ea-9b6f-250dec7cdeab.png)

系統管理可以選擇後，防汛工具放大鏡統計表格又出現"選擇"欄

**Comment by EideWang** [comment]
先點開防汛工具自主防災社區放大鏡統計表格
再去系統管理-自主防災社區管理
系統管理那邊的modal會無法正常選取row(必須重新整理重開modal才能選取)

**Comment by karateboy** [comment]
bootstrap bug....

**Comment by karateboy** [comment]
fixed 0525

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82852160-b27eed80-9f34-11ea-8b8b-83254fe51864.png)

放大鏡那邊又冒出不該有的選取功能(然後會連動系統管理那邊)...

**Comment by karateboy** [comment]
可選取 但下方無可以刪除的按鈕，功能不影響. 這是Bootstrap vue的bug, 已經奮鬥很久無法解決

**Comment by karateboy** [comment]
fixed 0527

**Comment by EideWang** [comment]
C哥真猛
