### ISSUE TITLE
[水位橫斷面] 展示方式調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#375]
![image](https://user-images.githubusercontent.com/28863560/82624319-cf55b100-9c14-11ea-93a0-36bb335f733a.png)
目前看來展示方式是對的
麻煩C哥再修正，水位那條線不是area填滿，底床才是

**Comment by EideWang** [comment]
@karateboy  底床高度最低的應該是-3.85m，底床那條線的area填滿可考慮以-5取代0作為基準線

另，橫斷面底床未填色，fill:#ab60059e

**Comment by karateboy** [comment]
fixed 0526

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82975486-30172c00-a00f-11ea-8731-7382abf2f6af.png)

**Comment by karateboy** [comment]
fixed 0527
