### ISSUE TITLE
[討論] 測站套疊於地圖上的切換速度疑問

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#378]
9個主功能button有設定點擊後套疊測站的功能(例如點擊雨量資訊，會自動套疊雨量站分布圖)
再切不同主功能button時，常常轉圈圈轉好幾秒(即時監控特別明顯)；之前有說是因為要一次載入所有測站資料的緣故...但我"圖層"勾選各類型測站圖層來套疊，一勾馬上就能套疊，點擊icon也能彈出infobox，操作速度比起使用主功能button來說快上非常多，不知道兩者之間的差異是..?

**Comment by karateboy** [comment]
按主功能鍵會重新從API抓測站資料. 所以會轉很久. 
圖層勾選是利用已經抓到的資料, 把測站畫出來.
程式一開始的時候會先在背景抓各種測站資料存在記憶體中. 不會"轉"

若使用者在測站資料還沒抓回來之前, 從圖層切換測站顯示, 會顯示不出來. 等到資料抓到才會顯示.
