### ISSUE TITLE
[UI優化] 雨量資訊-即時報表

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#379]
![image](https://user-images.githubusercontent.com/28863560/82641252-a8ac7000-9c3e-11ea-97de-0c1fae48ac2e.png)

**Comment by karateboy** [comment]
fixed

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82770040-a8dc8380-9e69-11ea-89d6-d3f2cdc9dc0b.png)

目前展示成果很突兀

**Comment by EideWang** [comment]
改回原先表格

**Comment by karateboy** [comment]
fixed
