### ISSUE TITLE
[重要]瀏覽器的Navigator Bar沒有作用

### ISSUE THREAD

**Issue by PerryWu** [karateboy/ylfs_demo#38]
Case 1
![image](https://user-images.githubusercontent.com/11898742/70856772-b5090000-1f1d-11ea-8521-dcc285114c9e.png)
上一頁後
![image](https://user-images.githubusercontent.com/11898742/70856775-c2be8580-1f1d-11ea-8df2-05696ccb3d62.png)

Case 2
Login page -> site page -> map page
![image](https://user-images.githubusercontent.com/11898742/70856779-dc5fcd00-1f1d-11ea-8182-b0df73fbc158.png)
再map page 無法上一頁回 site page

**Comment by karateboy** [comment]
SPA後, 前一頁和後一頁的瀏覽已經變調. 因為所有的網頁對瀏覽器來說, 就只有一頁.
要讓瀏覽器的前後頁有意義. 需要額外規劃. 短期內無法修正

**Comment by karateboy** [comment]
關於SPA和前後鍵
https://medium.com/young-coder/a-simple-introduction-to-the-history-api-in-javascript-85b879d3d87e

**Comment by karateboy** [comment]
quick fix是把back button停掉
https://jes.al/2016/03/preventing-back-button-navigation-in-SPAs/

**Comment by karateboy** [comment]
以向後按鈕, 跳出警告. 待第二期重新規畫

**Comment by karateboy** [comment]
fixed in v0.1.0101
