### ISSUE TITLE
[UI優化] 水位資訊-即時報表-縣管水位站

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#380]
![image](https://user-images.githubusercontent.com/28863560/82641715-5d469180-9c3f-11ea-81b3-1b02797b532a.png)

**Comment by karateboy** [comment]
同中央管水位站

**Comment by EideWang** [comment]
不改active，只將default黑色改成#192E5B

**Comment by karateboy** [comment]
0610
