### ISSUE TITLE
[UI優化] 水位資訊-即時報表-中央管水位站

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#381]
![image](https://user-images.githubusercontent.com/28863560/82642054-dfcf5100-9c3f-11ea-863f-48439a795924.png)

**Comment by karateboy** [comment]
fixed Active顏色整個影響很大....不建議換

**Comment by karateboy** [comment]
比方說這個連結的顏色都會變成黑色....和使用者習慣整個翻掉
![image](https://user-images.githubusercontent.com/1067042/82726764-d960d800-9d18-11ea-8f18-bd2122a73aab.png)
