### ISSUE TITLE
[重要]開啟info box的視窗 預設沒有於畫面中間 要看內容還要滑動螢幕

### ISSUE THREAD

**Issue by PerryWu** [karateboy/ylfs_demo#39]
case 1
點擊後開到右邊上角去了
![image](https://user-images.githubusercontent.com/11898742/70856803-3cef0a00-1f1e-11ea-8661-8330f1842610.png)

case 2
點擊左上方的 camera
info box只有一點點.
![image](https://user-images.githubusercontent.com/11898742/70856814-64de6d80-1f1e-11ea-8e02-06d880952cc4.png)

**Comment by karateboy** [comment]
其實是有的, 左側的選單會讓測站點放在地圖正中央.  因為InfoBox太長, 才沒有感覺.
直接點擊其他測站, 不應該把該點設成螢幕中心. 因為這樣會造成地圖移動...

換言之, 要改善的是減少InfoBox的長度. 要不然這問題始終會存在.

**Comment by EideWang** [comment]
仍未正確呈現於正中間
![image](https://user-images.githubusercontent.com/28863560/70878663-56b34e80-1ffd-11ea-966b-96ef5190e3e8.png)

**Comment by karateboy** [comment]
@Zunnex 測站的位置有放在螢幕中央, (原本是放在螢幕正中央, 現在已經改成中間偏下方)
要將InfoBox放在畫面中央, 技術上有困難.
因為TGOS是地圖坐標系, 我不知道InfoBox的大小, 也不知道目前地圖放大縮小的程度. 所以我只能大概猜, 地圖中心要在緯度偏北的地方.

**Comment by karateboy** [comment]
已經改用Modal fixed in v0.1.1226_1
