### ISSUE TITLE
[UI優化] 搜尋紐優化

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#391]
![image](https://user-images.githubusercontent.com/28863560/82770329-bd6d4b80-9e6a-11ea-9788-21cdeed7bb99.png)

**Comment by karateboy** [comment]
搜尋按鈕bootstrap 沒有直接支援icon 
bootstrap vue的附加圖示也覺得這樣ok...我沒招了
https://bootstrap-vue.org/docs/components/input-group#using-prepend-and-append-props

**Comment by EideWang** [comment]
消藍框
.form-control:focus {
    outline: 0 !important;
    border-color: initial;
    box-shadow: none;
}

**Comment by karateboy** [comment]
fixed 0611
