### ISSUE TITLE
[UI優化] 水位警戒表格

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#393]
![image](https://user-images.githubusercontent.com/28863560/82802771-01377380-9eb2-11ea-8396-b9385cb4340d.png)

**Comment by karateboy** [comment]
fixed 0525

**Comment by EideWang** [comment]
@karateboy  一級警戒、二級警戒顏色都沒有改到

**Comment by karateboy** [comment]
fixed 0526
