### ISSUE TITLE
[UI優化] 雨量站infobox

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#395]
![image](https://user-images.githubusercontent.com/28863560/82803898-e82fc200-9eb3-11ea-8866-18a50f7d7ba0.png)

**Comment by EideWang** [comment]
過去累積雨量，font-weight: bolder

**Comment by karateboy** [comment]
我覺得你最近才改過....

**Comment by EideWang** [comment]
@karateboy  C哥，原本在issue#364有要改這一塊，原先是以22px/14px，當時你改的時候全部都改成22px，"過去累積降雨"則沒改到，那個issue比較大，所以先close，再發一次
避免不知道已經改了什麼，修正的部分我就接著發在這

![image](https://user-images.githubusercontent.com/28863560/82851269-ddb40d80-9f31-11ea-9238-5376817109c9.png)

**Comment by karateboy** [comment]
fixed 0526

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82969204-add43b00-a001-11ea-9e95-f206ff286305.png)

**Comment by karateboy** [comment]
fixed 0527

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82989525-6a8fc180-a02d-11ea-9440-bf54f530280d.png)
紅圈顏色沒改到

**Comment by karateboy** [comment]
fixed 0527
