### ISSUE TITLE
[UI優化] 縣管水位站infobox

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#396]
![image](https://user-images.githubusercontent.com/28863560/82804425-db5f9e00-9eb4-11ea-9f67-04fc2e145287.png)

**Comment by karateboy** [comment]
fixed 0526

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82968328-a449d380-9fff-11ea-907a-7ea53bb10016.png)

1. 圖標題18px (淹水感測infobox的效果很好)
2. 紅圈處的字型、顏色修正

**Comment by karateboy** [comment]
fixed 0527
