### ISSUE TITLE
[UI優化] 中央管水位站infobox

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#397]
![image](https://user-images.githubusercontent.com/28863560/82804766-73f61e00-9eb5-11ea-8dc7-aae15c3295aa.png)

**Comment by karateboy** [comment]
fixed 0527

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82968415-e3782480-9fff-11ea-87a6-a945ac2e9669.png)

1. 紅框處圖標題18px
2. 紅圈處字體、顏色沒改到

**Comment by karateboy** [comment]
fixed 0527
