### ISSUE TITLE
[UI優化] 潮位站infobox

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#398]
![image](https://user-images.githubusercontent.com/28863560/82805058-ef57cf80-9eb5-11ea-8a0c-b55fb65364f0.png)

**Comment by karateboy** [comment]
位置描述, 可能很長. 請參考麥寮巢位站

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82968586-38b43600-a000-11ea-8dee-281882565e8e.png)

1. 紅框處圖標題 18px
2. 紅圈處字體、顏色沒改到(微軟正黑 #192E5B)

**Comment by karateboy** [comment]
fixed 0527

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82982316-817be700-a020-11ea-8fad-711db452d248.png)


3個紅圈處 "水位" 改成 "潮位"
所以圖標題會變成 "麥寮潮位站 潮位歷線圖"
Y軸標題會變成"即時潮位(m)"

改完這個就大功告成了！
