### ISSUE TITLE
[UI優化] 淹水感測器infobox

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#399]
![image](https://user-images.githubusercontent.com/28863560/82806267-fe3f8180-9eb7-11ea-81ce-7fbb76881254.png)

**Comment by karateboy** [comment]
因為我是依照API回應的速度, 先回答得先畫線.
要固定順序, 就要依序等待. (損失是等待時間變更久)

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/82968179-474e1d80-9fff-11ea-9d13-7f7d5760bd78.png)

P.S. 還是需要依序等待，統一順序

**Comment by karateboy** [comment]
fixed 0527
