### ISSUE TITLE
Loading 時，沒有任何Loading Icon or 提示

### ISSUE THREAD

**Issue by PerryWu** [karateboy/ylfs_demo#40]
![image](https://user-images.githubusercontent.com/11898742/70856898-9efc3f00-1f1f-11ea-876d-3b55a20d7647.png)
在水閘門 跟 移動抽水機 點擊切換
modal都要等一陣子才會彈出，應該是在跟後台資料

但，沒有Loading的提示，還以為是該功能沒有實作 
請一致化提供所有需要長時間動作的頁面，都有Loading提示

**Comment by karateboy** [comment]
不是的, 因為server的API沒有做出來. @flyingapsara 建議放上假頁面, 假頁面太大, 就造成這樣的結果. 
會想辦法弄一個假的loading...但這是woraround, 因為主因是假頁面太大, VUE要完整載入頁面時, 才會顯示loading spinner. 這時使用者已經等很久了.  所以是"假loading"

**Comment by karateboy** [comment]
實驗後, 效果很差. 因為Load page會占用CPU 資源. spinner的無法即時顯示
建議workaround成把假頁面減肥

**Comment by karateboy** [comment]
或將JSON放在IIS 上, 作為server api的替代品

**Comment by karateboy** [comment]
已經加入Spinner, 但顯示有時快, 有時慢. 
無法複製實際的問題. 可能原因是瀏覽器快取的效應
放上IIS後, 網路傳輸的時間還不到30ms,
