### ISSUE TITLE
[UI優化] 五河局、防災中心淹水感測infobox

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#401]
![image](https://user-images.githubusercontent.com/28863560/82968897-e6274980-a000-11ea-856f-e4ddd85232d2.png)

1. 紅圈處顏色尚未修正
2. 作圖不顯示打點(與其他highchart展示方式統一)
3. 五河跟防災中心的淹水感測站都要修正(因為不知道是不是同一個模組，所以issue就開一起)

**Comment by karateboy** [comment]
fixed 0527
