### ISSUE TITLE
[UI優化] 溪流大排 縱斷面

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#402]
![image](https://user-images.githubusercontent.com/28863560/82974094-b7fb3700-a00b-11ea-9f2e-cef60b561394.png)

**Comment by EideWang** [comment]
1. 資料展示只展示T2~T7，修改名稱
2. 字型、顏色修正(微軟正黑 #192E5B)
3. 圖標題18px
4. 河床向下填色，#ab60059e

**Comment by karateboy** [comment]
fixed 0527

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/83126273-2ecb2980-a10b-11ea-8a5d-8a916291fb65.png)

X軸標題不顯示(因為難以定義)
Y軸標題改為"水位(m)"
缺這兩項大功告成！

**Comment by karateboy** [comment]
fixed 0528
