### ISSUE TITLE
[UI優化] 圖層展示風格統一

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#406]
![image](https://user-images.githubusercontent.com/28863560/83210552-c40f0200-a18d-11ea-9e70-cf8f1b995c79.png)

麻煩C哥以上圖展示方式調整(齊頭，文字無hover/active效果)，業主抱怨新加入的圖層清單很醜

**Comment by EideWang** [comment]
此外，目前測試"全選"、"清除所有圖層"的功能無法套用於新增的圖層中

**Comment by karateboy** [comment]
fixed

> 此外，目前測試"全選"、"清除所有圖層"的功能無法套用於新增的圖層中

雨量預報個圖層是互斥的....全選和清除在這有問題

**Comment by karateboy** [comment]
fixed

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/83367700-75a96f80-a3e8-11ea-9a03-dec4f0c3c468.png)
![image](https://user-images.githubusercontent.com/28863560/83367763-c28d4600-a3e8-11ea-9848-7fbb251ab263.png)

**Comment by karateboy** [comment]
fixed
