### ISSUE TITLE
[UI優化] 網站頁簽VUE logo更換

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#407]
把VUE綠V的logo更換為下面的ico檔(雲林logo的火把)
https://drive.google.com/drive/u/0/folders/1QI67IgYiV3sZvrgRGIJtuisDd-oIf6S9

**Comment by karateboy** [comment]
favicon.ico 包含不只一個icon
https://drive.google.com/open?id=14edJ9bk6FfbdkvvAP5tl2M1kHIRoYNKq&authuser=karateboy%40sagainfo.com.tw&usp=drive_fs

**Comment by karateboy** [comment]
必須提供完整的這一套icon來更換. 另外favicon.ico 瀏覽器只會讀一次, 從此快取起來再也不更新....

**Comment by karateboy** [comment]
建議有空再換

**Comment by karateboy** [comment]
0610

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84361991-170d9e00-abff-11ea-9f51-87e0a93e2c0f.png)

登入頁面跟單一入口網有變，但智慧防汛整合平台卻沒有??!

**Comment by karateboy** [comment]
智慧防汛整合平台 已經更新
