### ISSUE TITLE
[緊急]"資料時間"有誤

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#41]
![image](https://user-images.githubusercontent.com/28863560/70872889-e3521280-1fe5-11ea-9c96-963c7e0eaacb.png)

末端時分秒部分，請修正為容易閱讀的格式(不要有莫名的英文字母)

**Comment by karateboy** [comment]
fixed in v0.1.1223

**Comment by EideWang** [comment]
修正後時間顯示錯誤
![image](https://user-images.githubusercontent.com/28863560/71396633-dd97a500-2655-11ea-9e18-ee6cb9b8e943.png)
此外，雨量和水位的即時報表時間欄位亦須執行相同修正，使其容易閱讀

**Comment by karateboy** [comment]
fixed in v0.1.1225

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/71447618-8be13e80-276b-11ea-8b78-db4189aa3fc3.png)
目前各個infobox與雨量、水位即時報表所抓到的時間仍然是錯誤的

**Comment by karateboy** [comment]
@Elvis0059 麻煩修正時區問題 謝謝

**Comment by Elvis0059** [comment]
已修正Timestamp的時區格式，如下圖：
![1577341565557](https://user-images.githubusercontent.com/57971834/71461905-85df7200-27ec-11ea-946f-9a9cafb22067.jpg)
