### ISSUE TITLE
[雨量警戒] 淹水警戒通知紀錄 功能異常 

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#415]
![image](https://user-images.githubusercontent.com/28863560/83382389-95a35800-a415-11ea-8b35-81179de19f9c.png)

防汛平台查無任何歷史資料
但確認Senslink 3.0 是有紀錄的
![image](https://user-images.githubusercontent.com/28863560/83382421-aa7feb80-a415-11ea-8898-b293b4fe1041.png)

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/83425528-6c5be980-a460-11ea-99ed-d59af8ed63d3.png)
傳入參數看起來都是正確的

**Comment by karateboy** [comment]
回傳為空陣列

**Comment by Elvis0059** [comment]
是我API這沒寫好，已調整，請確認。
![2020-06-02_100756](https://user-images.githubusercontent.com/57971834/83472089-00599f80-a4b9-11ea-9a6d-39f771966793.jpg)
