### ISSUE TITLE
[抽水機調度] 功能修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#418]
1. 目前的啟閉操作方式，使用者很難判斷是開啟還是關閉，建議改以下圖方式實作
![image](https://user-images.githubusercontent.com/28863560/83469253-c33ddf00-a4b1-11ea-9f12-04ae65037469.png)

2. 右下方的總抽水能量沒有隨抽水站抽水能量變化而跟著變化

3. 手動建議值(台)計算錯誤，且沒有隨抽水站抽水能量變化而跟著變化

4. 手動建議值(台) 沒有隨抽水機台數增加而跟著變化

5. 模式建議值(台)計算錯誤
![image](https://user-images.githubusercontent.com/28863560/83469784-2da34f00-a4b3-11ea-8ae5-6955b456e941.png)

6. 左側地圖沒有顯示全部淹水量體範圍，無法點擊後展示該淹水量體
![image](https://user-images.githubusercontent.com/28863560/83470054-d05bcd80-a4b3-11ea-9c46-c863a65bad67.png)

**Comment by karateboy** [comment]
fixed 0602

**Comment by EideWang** [comment]
目前移動式抽水機數量上限只能到100，請改無上限
其他目前看都正確

**Comment by karateboy** [comment]
spin button無法設定無上限, 我設定成10000 應該足夠
