### ISSUE TITLE
[緊急]天氣概況所套疊的雷達回波圖是錯誤的

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#42]
![image](https://user-images.githubusercontent.com/28863560/70872943-2f9d5280-1fe6-11ea-8701-5953cc628ea3.png)

此圖不會自動更新

**Comment by karateboy** [comment]
這圖是 @flyingapsara  提供的, 如果你知道其他的雷達迴波圖. 請提供.

**Comment by flyingapsara** [comment]
該圖目前來源一直未更新
因此還是使用這套好了

https://opendata.cwb.gov.tw/dataset/observation/O-A0059-001

若有延遲就轉圈圈即可

**Comment by karateboy** [comment]
@flyingapsara 抓取Open Data 套圖, 最穩當的作法是由server定期抓資料產生套圖. 前端再透過這張圖套疊到地圖上. 
@Elvis0059 請評估定期抓資料, 產生套疊圖所需要的時間. 
@Zunnex 這個功能很花時間! 這個問題雖然是發生在12/13前, 但Open Data整合並不是那麼容易, 還需要額外的功夫畫圖和處理各種網路連線錯誤的狀況. 希望你可以跟承辦溝通
