### ISSUE TITLE
[UI優化] 淹水量體分析

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#420]
![image](https://user-images.githubusercontent.com/28863560/83470562-17968e00-a4b5-11ea-962a-93de260be9ff.png)

業主反應目前呈現結果很醜，換行換得很亂、不整齊
應該縮小右邊勾選區每個item間距，讓右邊區域排列緊密點，增加左側的空間佔比
或是C哥有更好的實作建議呢?

2. 平方公尺、立方公尺的單位，多了空格(?)
![image](https://user-images.githubusercontent.com/28863560/83470989-1a45b300-a4b6-11ea-9bdf-a303af7c5a75.png)

**Comment by karateboy** [comment]
fixed 0602
