### ISSUE TITLE
[UI優化] 歷史水位查詢-縣管水位站

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#422]
![image](https://user-images.githubusercontent.com/28863560/83472509-fdab7a00-a4b9-11ea-8918-c7aad40c4798.png)

1.  移除警戒線的打點
2. 移除未來1~5小時作圖打點
3. 警戒線顏色修改成與水位infobox統一

**Comment by karateboy** [comment]
fixed 0609
