### ISSUE TITLE
[歷史水位資料] 中央管水位站 查詢時查不到警戒線以外的物理量

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#423]
查詢時查不到警戒線以外的物理量
是否API介接錯誤?

**Comment by EideWang** [comment]
雲嘉大橋
田頭橋
善功橋
梅南橋
雙東大橋
西結橋
大湖口溪橋
@karateboy 
此五站API查有資料，但防汛平台查詢卻無法顯示，麻煩C哥確認介接的正確性

**Comment by karateboy** [comment]
因為警戒值為文字, 造成前端錯誤

**Comment by karateboy** [comment]
fixed 0604
