### ISSUE TITLE
[UI優化] 歷史淹水感測資料

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#428]
![image](https://user-images.githubusercontent.com/28863560/83475920-f2f4e300-a4c1-11ea-8144-7628265a28c2.png)

1. 警戒線移除打點
2. 警戒線顏色調整為和淹水感測infobox一樣
3. 淹水深度顯示位數調整
4. 訊號強度顯示位數調整

**Comment by karateboy** [comment]
fixed 0609
