### ISSUE TITLE
[緊急]水利建造物檢查文字描述未實作且缺少門檻值

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#43]
![image](https://user-images.githubusercontent.com/28863560/70873087-e4d00a80-1fe6-11ea-8ddf-9bc1467e60f6.png)

**Comment by EideWang** [comment]
缺少門檻值
![image](https://user-images.githubusercontent.com/28863560/70879206-72b7ef80-1fff-11ea-84e1-d265bd29b112.png)

**Comment by karateboy** [comment]
fixed v0.1.1223
