### ISSUE TITLE
[水位資訊] 即時報表 縣管水位站、中央管水位站 的堤頂高沒有正確顯示

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#431]
![image](https://user-images.githubusercontent.com/28863560/83487869-70c6e780-a4de-11ea-82ac-3a2742013f57.png)

縣管水位站、中央管水位站 的堤頂高 沒有正確顯示，之前有但現在消失了

**Comment by EideWang** [comment]
另，麻煩column title 堤頂高加上單位 --->  "堤頂高(m)"

**Comment by karateboy** [comment]
fixed 0603
