### ISSUE TITLE
[文字修正] 鄉鎮市統計、村里統計 冗空格移除

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#438]
![image](https://user-images.githubusercontent.com/28863560/83623614-2029ba00-a5c4-11ea-98d2-ab70c5ce523a.png)

![image](https://user-images.githubusercontent.com/28863560/83623653-2fa90300-a5c4-11ea-9ab3-da0d8869a1e5.png)

**Comment by karateboy** [comment]
fixed 0604
