### ISSUE TITLE
[緊急]雨量警戒並未實作表格

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#44]
![image](https://user-images.githubusercontent.com/28863560/70873658-a720b100-1fe9-11ea-8b7e-657907d133f9.png)

目前仍是圖片假頁面，沒有實作表格及功能

**Comment by karateboy** [comment]
警戒資訊, 第一期不做?

**Comment by EideWang** [comment]
表格類判定需要做
如水位
![image](https://user-images.githubusercontent.com/28863560/70873992-164ad500-1feb-11ea-8253-03d69a056044.png)

**Comment by karateboy** [comment]
@Elvis0059 請跟 @Zunnex 討論確定API是否要實作. 或者只需要空的頁面框架

**Comment by Elvis0059** [comment]
雨量鄉鎮警戒API已上版，如下圖，請整合看看，
跟kaka確認過，只需回傳警戒的行政區。
![20191223_yunlin_rain_alert](https://user-images.githubusercontent.com/57971834/71333421-e5334d00-2574-11ea-80ab-60d165d89473.jpg)

**Comment by karateboy** [comment]
fixed in v0.1.1226

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/71452392-ac3ae880-27bf-11ea-9b05-5ce59fb82ed6.png)
因為API回傳直接是行政區，所以表格不用再寫出，也不用有"測站"欄

**Comment by karateboy** [comment]
fixed in v0.1.1226_1
