### ISSUE TITLE
[淹水量體分析] 淹水區塊消失

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#442]
![image](https://user-images.githubusercontent.com/28863560/84102682-b8e88b80-aa43-11ea-9986-349263a8e230.png)

原先有兩個，但點擊其中一個跳過去後，另一個淹水區塊就不見了
![image](https://user-images.githubusercontent.com/28863560/84102725-d1f13c80-aa43-11ea-88ac-48c0b4a1171d.png)

地圖應常駐顯示所有淹水區塊

**Comment by karateboy** [comment]
fixed 0609
