### ISSUE TITLE
[單一入口網] 缺是否為管理者

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#446]
![image](https://user-images.githubusercontent.com/28863560/84133353-a5f0ae00-aa79-11ea-8f46-70709a6279b2.png)
table少一欄是否為管理者

![image](https://user-images.githubusercontent.com/28863560/84133504-d7697980-aa79-11ea-9874-1fb87fec6c23.png)
管理者在管理使用者時，編輯該使用者是否成為管理者的選項不見了

另，"更新使用者" title文字格式明顯與其他不一致

**Comment by karateboy** [comment]
這和先前不能變更身分為管理者是互斥的...

**Comment by karateboy** [comment]
0610
