### ISSUE TITLE
[UI優化] 淹水量體分析-鄉鎮市/村里分析

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#448]
![image](https://user-images.githubusercontent.com/28863560/84136488-f2d68380-aa7d-11ea-805b-183af2799fb6.png)

1. EXCEL置右
2. 預報時間、選單相鄰，選單寬度抓一下(格式固定都是那麼長，所以不要fullfill)
3. 1跟2同一列

**Comment by karateboy** [comment]
0610

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84227927-40073380-ab18-11ea-9431-e9b81207982e.png)
我把文字說明畫成圖C哥應該比較好理解
目前改的結果跟上面的範例圖差蠻多的，請再調整，謝謝

**Comment by karateboy** [comment]
fixed 0610

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84345907-3e557280-abe1-11ea-966a-1c3c3db67db7.png)

![image](https://user-images.githubusercontent.com/28863560/84345849-09492000-abe1-11ea-9b37-2c370dd90b5a.png)

鄉鎮市分析、村里分析  紅圈處左邊兩個物件沒垂直置中，導致左右沒水平

**Comment by karateboy** [comment]
fixed 0611
