### ISSUE TITLE
[緊急]系統管理-使用者資訊與下方button錯字

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#45]
![image](https://user-images.githubusercontent.com/28863560/70875691-c6bbd780-1ff1-11ea-97db-ddd61c0f6c66.png)

這裡資訊空白的話業主驗收無法通過
前三項可以寫死，但後三項請共商如何完成，感謝!

**Comment by EideWang** [comment]
"上次登入"因涉及資料庫不易實作，這期先移除該項目，僅留前五項

**Comment by karateboy** [comment]
@Elvis0059 請實作API
GET /v1/api/account/userinfo

並請增加相關欄位

**Comment by EideWang** [comment]
使用者：游景年
部門：水利管理科

**Comment by EideWang** [comment]
"歷史報表管理"
![image](https://user-images.githubusercontent.com/28863560/71144477-1c45ed80-2259-11ea-961c-b25d1592731f.png)

**Comment by EideWang** [comment]
另修改
"路面淹水警戒管理"
![image](https://user-images.githubusercontent.com/28863560/71144547-6038f280-2259-11ea-99a7-505b11f6aa10.png)

**Comment by Elvis0059** [comment]
> @Elvis0059 請實作API
> GET /v1/api/account/userinfo
> 
> 並請增加相關欄位

API已上版，已同步更新API文件，請確認。
![2019-12-20_userinfo](https://user-images.githubusercontent.com/57971834/71243836-272d7a80-234c-11ea-803f-f4e389fa1e17.jpg)

**Comment by karateboy** [comment]
fixed in v0.1.1225

**Comment by EideWang** [comment]
下方選項文字尚未修正
淹水警戒管理 >>路面淹水警戒管理
裡使圖表管理 >>歷史圖表管理

此外，"登入時間"與電腦系統時間不相符

**Comment by karateboy** [comment]
@Elvis0059 https://zh.wikipedia.org/wiki/ISO_8601
麻煩修正ISO8601時區問題
