### ISSUE TITLE
[UI優化] 移動式抽水機智慧調度

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#451]
![image](https://user-images.githubusercontent.com/28863560/84259930-c8eb9280-ab4b-11ea-9f00-3f31ca45bdd3.png)

**Comment by EideWang** [comment]
麻煩C哥能盡快改善UI，業主目前看到此UI情況仍然覺得我們是不是還在測試、是半成品

**Comment by karateboy** [comment]
0610

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84333769-40103d80-abc3-11ea-961a-56facee2056c.png)

**Comment by karateboy** [comment]
0611
