### ISSUE TITLE
[路面淹水警戒通知紀錄] 移除現無功能

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#453]
![image](https://user-images.githubusercontent.com/28863560/84337670-bbc2b800-abcc-11ea-8af5-8a87a18af3e4.png)

目前無法查詢>5cm及資料異常，請移除選項

**Comment by Elvis0059** [comment]
![2020-06-12_090941](https://user-images.githubusercontent.com/57971834/84454213-7e256400-ac8c-11ea-9c2a-bf9b4335d678.jpg)
這已經改過了，確認一下吧

**Comment by karateboy** [comment]
已修正
