### ISSUE TITLE
[UI優化] 歷史決策建議分析報告

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#454]
![image](https://user-images.githubusercontent.com/28863560/84346291-3b0eb680-abe2-11ea-9bc2-d8aeaae00be5.png)

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84346857-8ffefc80-abe3-11ea-9425-6b2a6810de92.png)

**Comment by karateboy** [comment]
0611
