### ISSUE TITLE
[UI優化] 歷史圖資資料

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#455]
![image](https://user-images.githubusercontent.com/28863560/84346581-e4ee4300-abe2-11ea-85e5-b33c0ac459ca.png)

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84843448-7b56b480-b07a-11ea-8d87-8bf1577686b7.png)
麻煩C哥放大圖例並調整一下位置，目前的大小跟位置讓人不值觀點擊下載
33.5*33.5px

**Comment by karateboy** [comment]
0617
