### ISSUE TITLE
NaN沒轉成顯示--

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#456]
![image](https://user-images.githubusercontent.com/28863560/84347014-0dc30800-abe4-11ea-8d01-66f916c19799.png)

之前有issue是要改這個，不清楚為何又變回來

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84368927-c26f2080-ac08-11ea-9b6f-fa41c55b97e2.png)

**Comment by karateboy** [comment]
API 所有丟的資料都有可能是NaN....前端根本在補破網

**Comment by karateboy** [comment]
已經根據這兩個圖補起來了
