### ISSUE TITLE
舊虎尾溪排水七、施厝寮排水四 橫斷面 error

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#457]
![image](https://user-images.githubusercontent.com/28863560/84347181-701c0880-abe4-11ea-8fcb-0606555f2b40.png)

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84368349-0877b480-ac08-11ea-92ea-6d133a7bf41d.png)
施厝寮排水四 同樣問題

**Comment by karateboy** [comment]
沒資料就不畫
