### ISSUE TITLE
不同溪流大排橫斷面切換時，內容不會更著換

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#458]
![image](https://user-images.githubusercontent.com/28863560/84347313-c2f5c000-abe4-11ea-9f61-acb88dba01b0.png)

點擊下一個溪流大排斷面icon時，應該刷新modal並default展示為縱斷面，目前如此操作只會換modal title

**Comment by karateboy** [comment]
fixed 0612
