### ISSUE TITLE
[淹水量體分析] 未default套疊第一個預報時間點的淹水模擬圖

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#462]
點擊"決策系統"跳出modal後，預設為淹水量體分析頁面，雖有實作切換預報時間會跟著套疊淹水深度圖，但進入時尚缺default套疊淹水深度圖(變的是要先切其他時間再切回來才能套疊)
![image](https://user-images.githubusercontent.com/28863560/84353891-8a5ce300-abf2-11ea-9c23-e7d0a9f28ca4.png)

**Comment by karateboy** [comment]
0612

**Comment by karateboy** [comment]
驗證方法
1. 進入前
![image](https://user-images.githubusercontent.com/1067042/84449552-4e705f00-ac80-11ea-8df9-cb0e1e864fbe.png)

**Comment by karateboy** [comment]
進入後 (已經套疊預報時間點)
![image](https://user-images.githubusercontent.com/1067042/84449581-61832f00-ac80-11ea-985c-387426411e0b.png)

**Comment by EideWang** [comment]
2020/06/16 測試此項目，功能未達成

有時有成功顯示，有時卻沒有，沒有的時候，會連同淹水區塊的圖層都沒顯示

**Comment by karateboy** [comment]
程式碼是一樣的....和前端無關
沒有的原因, 是因為疊圖失敗 (圖層是否產生成功? 圖層產生的速度是否太慢?)
