### ISSUE TITLE
[地圖] 新增雨量、淹水圖例

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#463]
![image](https://user-images.githubusercontent.com/28863560/84366597-a3bb5a80-ac05-11ea-8ab9-af24cf60920f.png)

參考展示方式如上圖

有三個地方需要放圖例
1. 整個畫面右下角 (淹水圖例+降雨圖例)
2. 淹水量體分析-鄉鎮市分析 的地圖右下角 (淹水圖例)
3. 移動式抽水機智慧調度 的地圖右下角 (淹水圖例)

淹水圖例級距
<0.15m  #c8c8c8 透明度25%
0.15m-0.3m #ffeecd
0.3m-0.5m #ffd380
0.5m-1m #fcba09
1m-2m #ff620b
2m-3m #fb1717
　>3m #850001

雨量圖例級距
0-1 #c9c9c9
1-2 #9dfdfe
2-6 #01d2fd
6-10 #00a5fe
10-15 #0177fd
15-20 #27a41c
20-30 #01fa30
30-40 #fefd31
40-50 #ffd328
50-70 #ffa71f
70-90 #ff2b06
90-110 #d92203
110-130 #aa1800
130-150 #aa21a3
150-200 #dc2dd2
200-300 #ff38fb
　>300 #ffd6fe

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84367806-5344fc80-ac07-11ea-8ddc-2f63d64e2090.png)

**Comment by karateboy** [comment]
fixed 0614
