### ISSUE TITLE
[總覽] 主控台、圖層、系統管理 切換時，不應關閉當前modal

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#465]
之前切換主控台、圖層、系統管理不會關閉當前modal，現在卻會，麻煩改回原本的
因為使用上會開著A測站infobox然後切換到"圖層"，或是開著"決策系統"modal然後使用圖層功能

**Comment by EideWang** [comment]
又壞了..到底...

**Comment by karateboy** [comment]
禮拜六  Perry要求rollback 就回到前一版了
