### ISSUE TITLE
[UI優化] 歷史圖資管理

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#468]
![image](https://user-images.githubusercontent.com/28863560/84479621-d4fb5f80-acc5-11ea-8542-7884e3c51f85.png)

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84966409-0e0f5600-b144-11ea-8c67-f033912ee02f.png)
未垂直置中

**Comment by karateboy** [comment]
已經置中, 但因為下方table 有margin 所以看起來沒有. 已把margin 移除

**Comment by EideWang** [comment]
同樣button margin 的問題
