### ISSUE TITLE
[嚴重]手機觀看目前是幾乎無法正常操作和顯示

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#47]
行動裝置正常觀看及操作為驗收重點項目之一，
請務必協助修正此功能！

**Comment by karateboy** [comment]
先前業主建議的控制排版, 在手機上是完全不行的. 例如原本B1, B2占用固定的畫面長度, 沒有scroll bar也是完全無法操作. 另外既有的button 字很長, 在手機畫面也變得很亂.

手機適合的介面是"圖示", 自動收放的menu bar. 請你們一起想想到底想要怎樣的操作介面.

**Comment by EideWang** [comment]
可向左收合，手機時能有較好體驗，使用js解決

**Comment by karateboy** [comment]
fixed in v0.1.1227
