### ISSUE TITLE
[緊急]雨量即時報表 > 缺少12小時與權責單位data，站碼抓錯

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#48]
如圖
![image](https://user-images.githubusercontent.com/28863560/70879074-0c32d180-1fff-11ea-9639-1c5b5a0b7acc.png)

**Comment by karateboy** [comment]
@Elvis0059 Server API 未提供該資料

**Comment by Elvis0059** [comment]
針對12小時累積雨量部分：
請參照下圖，因API確定有給出數值，應是前端資料對應問題?
![2019-12-17_112301](https://user-images.githubusercontent.com/57971834/70962440-35676680-20c0-11ea-9eef-502e8a479466.jpg)

**Comment by Elvis0059** [comment]
權責單位已提供，請確認。
![2019-12-17_122807](https://user-images.githubusercontent.com/57971834/70964942-deb25a80-20c8-11ea-849c-ea384f191da8.jpg)
