### ISSUE TITLE
[UI優化] 切換主控台、圖層、系統管理頁籤時，控制板不應閃爍

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#484]
目前切換這三個頁籤時，整個控制區有閃爍刷新情況
不應出現此問題
切換時底框不閃的展示如下連結(請忽略裡面文字切換時的特效)
http://www.jq22.com/yanshi123

**Comment by karateboy** [comment]
tab切換預設有fade 動畫
https://bootstrap-vue.org/docs/components/tabs

**Comment by karateboy** [comment]
不是閃爍....

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/84634463-6bc55780-af24-11ea-9ad3-83449a035320.png)
no fade?

**Comment by karateboy** [comment]
no fade
