### ISSUE TITLE
單一入口網-使用者平台查看權限管理

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#497]
單一入口網的「使用者管理」，新增使用者可以查看到哪些介接平台的權限設定(以勾選方式決定)；
部門之管理單位之新增選項部分，需由縣府提供要再額外新增的部門名稱/管理單位，再以程式碼修改更新選項。

**Comment by Elvis0059** [comment]
API已上版，請確認。

**Comment by karateboy** [comment]
fixed 0726
