### ISSUE TITLE
主控板使用到scroll bar的部分調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#5]
當樹狀結構展開超出固定主控板範圍時，需有scroll bar，請協助令scroll bar起始位置從樹狀結構開始(不要影響到A區及B1按鈕區)，且注意出現scroll bar時，主控板之寬度需維持一致而不會有些微變化。

**Comment by karateboy** [comment]
v.0.1.1127已修正

**Comment by PerryWu** [comment]
wrong remove... add fixed back

**Comment by karateboy** [comment]
v.0.1.1129_2已修正 (請參照https://yliflood.yunlin.gov.tw/Portal/)

**Comment by karateboy** [comment]
@Zunnex 這個issue 跟
https://github.com/karateboy/ylfs_demo/issues/12 重複. 關掉這個, 統一在12討論.
