### ISSUE TITLE
雨量-即時報表  修正擴充

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#506]
雨量資訊即時報表排序順序調整為：行政區、站碼、站名、累積雨量{過去10分鐘(mm), 過去1小時(mm) , 過去3小時(mm) , 過去6小時(mm) , 過去12小時(mm) , 過去24小時(mm)}、警戒狀態、權責單位、資料時間。

預設展示順序邏輯第一層為警戒狀態(一級警戒>二級警戒>無警戒)，第二層為行政區。

累積雨量、警戒狀態、資料時間需有排序功能。

警戒狀態指的是「鄉鎮市淹水警戒」(一級警戒、二級警戒)，以燈號表示，Excel表格下載則仍使用文字呈現。

表格上方新增展示篩選功能，包括：行政區篩選、權責單位篩選。

需有點擊table row彈出該測站資訊視窗、地圖移動至該點位置並zoom in。

**Comment by karateboy** [comment]
等待API 警戒狀態

**Comment by Elvis0059** [comment]
API已增加警戒狀態。

**Comment by karateboy** [comment]
fixed 0727
