### ISSUE TITLE
水位-即時報表-縣管水位站 修正擴充

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#507]
水位資訊-縣管水位站即時報表排序順序調整為：行政區、站碼、站名、即時水位(m)、三級警戒(m)、二級警戒(m)、一級警戒(m)、堤頂高(m)、警戒狀態、權責單位、資料時間。

預設展示順序邏輯第一層為警戒狀態(溢堤警戒>一級警戒>二級警戒>三級警戒>無警戒)，第二層為站碼。

警戒狀態、資料時間需有排序功能。

警戒狀態以燈號表示，Excel表格下載則仍使用文字呈現。

表格上方新增展示篩選功能，包括：行政區篩選、溪流/大排篩選。

需有點擊table row彈出該測站資訊視窗、地圖移動至該點位置並zoom in。

**Comment by karateboy** [comment]
fixed 0722

**Comment by EideWang** [comment]
C哥，展示的排序邏輯沒有設定到~

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/88247870-e7f44d00-ccd1-11ea-92ef-cacfbe7f83fb.png)
警戒的展示有BUG

**Comment by karateboy** [comment]
fixed 0723
