### ISSUE TITLE
水位-即時報表-潮位站 修正擴充

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#509]
水位資訊-潮位站即時報表排序順序調整為：行政區、站碼、站名、即時潮位(m)、權責單位、資料時間。

預設展示順序邏輯第一層為站碼。(僅兩站，不用特別排序)

需有點擊table row彈出該測站資訊視窗、地圖移動至該點位置並zoom in。

**Comment by karateboy** [comment]
fixed 0722
