### ISSUE TITLE
淹水感測-即時報表

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#512]
淹水感測即時報表排序順序調整為：行政區、站碼、站名、淹水深度(cm)、警戒狀態、權責單位、資料時間。

預設展示順序邏輯第一層為警戒狀態(危險>警戒>預警>反應>無警戒)，第二層為行政區，第三層為站碼。

淹水深度(cm)、警戒狀態、資料時間需有排序功能。

警戒狀態以燈號表示，Excel表格下載則仍使用文字呈現。

表格上方新增展示篩選功能，包括：行政區篩選、權責單位篩選。

需有點擊table row彈出該測站資訊視窗、地圖移動至該點位置並zoom in。

**Comment by karateboy** [comment]
@Zunnex 燈號圖示?

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/88247560-bf1f8800-ccd0-11ea-96f3-2dd5cfb11502.png)

展示邏輯排序未設定妥當
另，抱歉，展示邏輯我遺漏了"資料異常"這個類型，故展示的順序更新為：
預設展示順序邏輯第一層為警戒狀態(危險>警戒>預警>反應>資料異常>無警戒)，第二層為行政區，第三層為站碼。

**Comment by karateboy** [comment]
fixed 0723
