### ISSUE TITLE
暫時隱藏除了歷史淹水感測外的「查詢全部測站」功能

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#516]
暫時隱藏除了歷史淹水感測外的「查詢全部測站」功能(不要刪code，怕業主反悔)

**Comment by karateboy** [comment]
fixed 0722

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/88247511-8f708000-ccd0-11ea-8b39-e74a29b78c3d.png)

歷史雨量預報沒有藏到~

**Comment by karateboy** [comment]
fixed 0723
