### ISSUE TITLE
原水位橫斷面的物理量整併至水位站資訊視窗中

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#518]
![image](https://user-images.githubusercontent.com/28863560/87890820-9e55f900-ca6a-11ea-81ec-e98370dc4ddc.png)

包括河床及模擬水位，需整合展示於水位站資訊視窗中
![image](https://user-images.githubusercontent.com/28863560/87890884-d65d3c00-ca6a-11ea-833d-f0956388e5a4.png)

**Comment by karateboy** [comment]
fixed 0726

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/88494452-c2748580-cfe8-11ea-86e8-1bb714847737.png)

怪異的狀況
另，右側看來沒有垂直自適應

**Comment by karateboy** [comment]
![image](https://user-images.githubusercontent.com/1067042/88502401-e93eb600-d000-11ea-91c8-5d03fe03fde9.png)

**Comment by karateboy** [comment]
@Zunnex 是你檢視的時候, 後臺預測資料還沒好. 不是我的問題. 另外圖片本來就有適當的"長寬比" 垂直留白是正常的
