### ISSUE TITLE
[淹水感測infobox] 新的備註功能，展示位置調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#519]
![image](https://user-images.githubusercontent.com/28863560/88247243-9945b380-cccf-11ea-80c2-43683742ad09.png)

"警戒備註"改成"備註"，因為這欄的功能用意是讓縣府填寫該測站特殊環境條件或是設備狀態/檢修時程等note，
展示順序移到"資料時間"下方(最後一個)

**Comment by karateboy** [comment]
fixed 0724
