### ISSUE TITLE
[嚴重]網頁 scrollbar style 調整

### ISSUE THREAD

**Issue by flyingapsara** [karateboy/ylfs_demo#52]
參考css如下
直接貼到css裡即可

::-webkit-scrollbar-track
{
	-webkit-box-shadow: inset 0 0 6px rgba(255,255,255,0.3);
	border-radius: 10px;
	background-color: rgba(255,255,255,0);
}

::-webkit-scrollbar
{
	width: 5px;
	background-color: #F5F5F5;
}

::-webkit-scrollbar-thumb
{
	border-radius: 5px;
	-webkit-box-shadow: inset 0 0 6px rgba(0,0,0,.3);
	background-color: #989898;
}

**Comment by karateboy** [comment]
fix in v0.1.1226
