### ISSUE TITLE
[系統管理] 抽水站管理 全面更新

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#524]
原先是統計表格，現改成逐站管理
欄位{站名, 經度, 緯度, 行政區, 站號, 村里, 設計抽水量, 總抽水量, 進水, 出水, 引水設施, 主油槽, 日用油槽, 現場環境, 動力電源, 備用電池, 建置年份, 保護村落, 設施照片}

**Comment by karateboy** [comment]
fixed 0728

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/88757527-dced6100-d198-11ea-95ea-e908eb8e7d61.png)
目前看沒有更新

**Comment by karateboy** [comment]
昨天休的還沒上去....下午更新
