### ISSUE TITLE
[緊急]左側樣式參考

### ISSUE THREAD

**Issue by flyingapsara** [karateboy/ylfs_demo#53]
左側樣式參考如圖：

底色為585858
字都白色fff
按鈕實心色
上方按鈕分開使用border與底色相同色1px來做分格
![messageImage_1576656493951](https://user-images.githubusercontent.com/7899496/71069304-6aa0b100-21b3-11ea-816c-820e46ee1a6d.jpg)

**Comment by EideWang** [comment]
css調整如圖
將上半及下半分別用div分開
高度為75vh，
下方則可用 calc( 75vh - 上方9個按鈕高度 )
並且 overflow auto
即可解決左側問題
![S__18211066](https://user-images.githubusercontent.com/7899496/71067388-696d8500-21af-11ea-989f-787ff76e407f.jpg)

**Comment by karateboy** [comment]
@flyingapsara 問題還是解一半, 因為有可能是2個b1按鈕, 1個b1按鈕 或沒有b1按鈕.
