### ISSUE TITLE
[緊急]登入及入口網圖片更換

### ISSUE THREAD

**Issue by flyingapsara** [karateboy/ylfs_demo#56]
換成這張

![tropical-beach-sunrise](https://user-images.githubusercontent.com/28863560/71241351-5e009200-2346-11ea-9394-8547c51bb71b.jpg)

**Comment by EideWang** [comment]
請取代連結平台之圖片
![bright-blue-day-water-rock (1)](https://user-images.githubusercontent.com/28863560/71241038-8a67de80-2345-11ea-9291-c5b93a50fdf9.jpg)
![motorized-water-sport](https://user-images.githubusercontent.com/28863560/71241040-8b990b80-2345-11ea-8742-79f7d82d9727.jpg)

人像圖片，並注意，請將人名"黃文宏"改成"游景年"
![boss](https://user-images.githubusercontent.com/28863560/71241238-1974f680-2346-11ea-9d82-01a01b1ca069.png)

**Comment by karateboy** [comment]
fixed in v0.1.1223
