### ISSUE TITLE
[緊急]所有即時報表、infobox的單位須要補上

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#60]
有不清楚的部分請立刻反應!

**Comment by karateboy** [comment]
麻煩列清單, 我好套用修改

**Comment by EideWang** [comment]
雨量即時報表&infobox：
過去累積10分 | 過去累積1小時 | 過去累積3小時 | 過去累積6小時 | 過去累積12小時 | 過去累積24小時
均加上 (mm)


水位即時報表&infobox：
即時水位 | 二級警戒值 | 一級警戒值 | 堤頂高
均加上 (m)

淹水感測infobox：
淹水高度
加上(cm)

**Comment by karateboy** [comment]
fixed in v0.1.1223

**Comment by EideWang** [comment]
雨量和水位的即時報表欄位仍未加入單位
