### ISSUE TITLE
[嚴重]淹水量體分析 、 抽水機調度建議要改放假圖(PM提供)

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#61]

**Comment by EideWang** [comment]
抽水機調度建議假圖：
![image](https://user-images.githubusercontent.com/28863560/71505354-ceb02d00-28b7-11ea-9d47-4b73a7ea2962.png)

**Comment by EideWang** [comment]
淹水量體分析假圖：
![image](https://user-images.githubusercontent.com/28863560/71505595-c5739000-28b8-11ea-8eed-87b6b8965e4f.png)

**Comment by karateboy** [comment]
fixed in v0.1.1229
