### ISSUE TITLE
[緊急] 淹水感測器infobox 高程單位，改成 m

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#66]

**Comment by EideWang** [comment]
另，所有infobox的冒號需要改成全形

**Comment by karateboy** [comment]
fixed in v0.1.1225

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/71447570-dd3cfe00-276a-11ea-8eca-047a840f9fb7.png)
淹水感測器infobox 高程單位沒有更改到

**Comment by karateboy** [comment]
不好意思, 漏改. 
Fixed in v0.1.1226

**Comment by EideWang** [comment]
目前看到尚未修正
![image](https://user-images.githubusercontent.com/28863560/71452482-764a3400-27c0-11ea-8690-1986569dccdf.png)

**Comment by karateboy** [comment]
fixed in v0.1.1226_1
