### ISSUE TITLE
[嚴重] 水位即時報表判定BUG

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#67]
![image](https://user-images.githubusercontent.com/28863560/71429850-b8fa0680-2703-11ea-8c4c-2d403e7e6b95.png)
如圖，打叉兩站都屬於"資料異常"狀態，因為時間並沒有跟其他水位站一樣即時更新，但卻顯示"正常"，此情況也沒反應在警戒資訊表格中。

另，水位數值請限制到小數點後兩位

**Comment by karateboy** [comment]
水位 小數位2位 fixed in v0.1.1225
@Elvis0059  關於報表, 請修正API回報內容. 謝謝

**Comment by Elvis0059** [comment]
資料異常增加判斷規則：
除資料為NaN外，若資料停止更新超過1小時，也視為資料異常。
預計於12/27(五)下班前調整。

**Comment by karateboy** [comment]
@Elvis0059 https://zh.wikipedia.org/wiki/ISO_8601
麻煩修正ISO8601時區問題

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/71567508-9a787e80-2afa-11ea-89e9-bc8f89e12fc8.png)
判定尚未解決
