### ISSUE TITLE
[普通] 移除TGOS地圖切換

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#74]
配合整體版面設計，暫定移除此項功能(不實用)
![image](https://user-images.githubusercontent.com/28863560/71573346-657e2300-2b1e-11ea-9261-5f02eb19ed71.png)

**Comment by flyingapsara** [comment]
其實我是覺得往下移就好了 XDD

**Comment by karateboy** [comment]
我先下移看看效果
