### ISSUE TITLE
[重要] CCTV infobox版面調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#75]
目前空白處過大，改成1*4目前滑鼠操作上使用滾輪不至於影響觀看
建議再調整放大影像圖片
![image](https://user-images.githubusercontent.com/28863560/71573506-361be600-2b1f-11ea-8dbd-b110d7f5d6ce.png)

**Comment by karateboy** [comment]
fixed in v0.1.1231
