### ISSUE TITLE
[重要] 移除通報紀錄假資料*3

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#76]
![image](https://user-images.githubusercontent.com/28863560/71573728-46809080-2b20-11ea-9e36-11203b67a3c9.png)
雨量警戒、水位警戒、路面淹水警戒
留一欄、內容空白(表現的項是還沒輸入時間區間所以沒資料展現那樣)

**Comment by karateboy** [comment]
fixed in v0.1.1231
