### ISSUE TITLE
[重要] 系統管理版面調整

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#77]
![image](https://user-images.githubusercontent.com/28863560/71573901-0d94eb80-2b21-11ea-9830-cde240255237.png)
調整如圖，欲讓版面的時間項不換行(左側空白過多)

**Comment by karateboy** [comment]
向左靠, 還是無法解決換行的問題...除非只顯示月/日 時間
![image](https://user-images.githubusercontent.com/1067042/71609420-3cfc3480-2bc3-11ea-8d1c-af71a239aaef.png)

**Comment by karateboy** [comment]
改用fromNow的方式.

**Comment by karateboy** [comment]
fixed in v0.1.0101

**Comment by EideWang** [comment]
看能否還是以日期時間呈現

**Comment by karateboy** [comment]
改回原本年月日, 最近不會遇到...因為現在是1月.... 要到10月才會遇到
fixed v0.1.0106
