### ISSUE TITLE
[重要] 登出鈕回到登入頁面

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#78]
希望讓系統管理>"登出" 按鈕點擊後能回到一開始帳密的頁面(目前是要重新整理後跑回登入頁面)
![image](https://user-images.githubusercontent.com/28863560/71574101-349fed00-2b22-11ea-96b5-7bfaf5622aa1.png)

**Comment by karateboy** [comment]
fixed in v0.1.1231
