### ISSUE TITLE
溪流/大排>放大鏡>縱斷面圖請更新為以下url；橫斷面下拉式選單內容更新各自所含的測站名稱，橫斷面圖片不須實作(無資料)

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#8]
1.	牛挑灣溪：
	縱斷面 http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=NeioTiewWen&rivername=%E7%89%9B%E6%8C%91%E7%81%A3%E6%BA%AA&model=T10
	牛挑灣溪一
	牛挑灣溪二
	牛挑灣溪三
	牛挑灣溪四
2.	尖山大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=GianShan&rivername=%u5c16%u5c71%u5927%u6392&model=T10
	尖山大排一
	尖山大排二
	尖山大排三
	尖山大排四
3.	蔦松大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=NiouSong&rivername=%u8526%u677e%u5927%u6392&model=T10
	蔦松大排一
	蔦松大排二
	蔦松大排三
	蔦松大排四
4.	施厝寮大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=SC&rivername=%u65bd%u539d%u5bee%u5927%u6392&model=T10
	施厝寮大排一
	施厝寮大排二
	施厝寮大排三
	施厝寮大排四
	施厝寮大排五
5.	有才寮大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=YuTsaiLiao&rivername=%u6709%u624d%u5bee%u5927%u6392&model=T10
	有才寮大排一
	有才寮大排二
	有才寮大排三
	有才寮大排四
	有才寮大排五
	有才寮大排六
	有才寮大排七
6.	馬公圳大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=MaGong&rivername=%u99ac%u516c%u539d%u5927%u6392&model=T10
	馬公圳大排一
	馬公圳大排二
	馬公圳大排三
	馬公圳大排四
	馬公圳大排五
	馬公圳大排六
	馬公圳大排七
7.	新虎尾溪：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=HsinHuWeiSi&rivername=%u65b0%u864e%u5c3e%u6eaa&model=T10
	新虎尾溪一
	新虎尾溪二
	新虎尾溪三
	新虎尾溪四
	新虎尾溪五
	新虎尾溪六
	新虎尾溪七
8.	舊虎尾溪：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=Johowei&rivername=%u820a%u864e%u5c3e%u6eaa&model=T10
	舊虎尾溪一
	舊虎尾溪二
	舊虎尾溪三
	舊虎尾溪四
	舊虎尾溪五
	舊虎尾溪六
	舊虎尾溪七
	舊虎尾溪八
9.	羊稠厝大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=Yang&rivername=%u7f8a%u7a20%u539d%u5927%u6392&model=T10
	羊稠厝大排一
	羊稠厝大排二
	羊稠厝大排三
10.	湳仔大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=NanZi&rivername=%u6e73%u4ed4%u5927%u6392&model=T10
	湳仔大排一
	湳仔大排二
	湳仔大排三
11.	客仔厝大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=KeZiChu&rivername=%u5ba2%u4ed4%u539d%u5927%u6392&model=T10
	客仔厝大排一
	客仔厝大排二
	客仔厝大排三
12.	新街大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=XinJie&rivername=%u65b0%u8857%u5927%u6392&model=T10
	新街大排一
	新街大排二
	新街大排三
13.	延潭大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=Yantan&rivername=%u5ef6%u6f6d%u5927%u6392&model=T10
	延潭大排一
	延潭大排二
	延潭大排三
14.	八角亭大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=BaJiaoTing&rivername=%E5%85%AB%E8%A7%92%E4%BA%AD%E5%A4%A7%E6%8E%92&model=T10
	八角亭大排一
	八角亭大排二
15.	大義崙大排：
	縱斷面http://210.61.11.56/yunlinFlood/%E6%B0%B4%E4%BD%8D%E8%B3%87%E8%A8%8A/WaterInfoChartVertical.aspx?riverType=DaYiLun&rivername=%u5927%u7fa9%u5d19%u5927%u6392&model=T10
	大義崙大排一
	大義崙大排二

**Comment by karateboy** [comment]
是測站橫斷面的圖在哪?

**Comment by karateboy** [comment]
還有應該是"縱斷面更新成url" 而不是橫斷面?

**Comment by karateboy** [comment]
Fix in v0.1.1203

**Comment by flyingapsara** [comment]
由於圖片畫素目前沒有很高
再請協助將 modal-xl 改成 modal-lg

**Comment by karateboy** [comment]
fixed in v 0.1.1210_1
