### ISSUE TITLE
[重要] 淹水警戒排版重新設計，目前有破版問題

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#80]
麻煩C哥規劃一下，處理破版問題，謝謝
![image](https://user-images.githubusercontent.com/28863560/71799027-0de83600-308f-11ea-9187-59080658fe87.png)

**Comment by karateboy** [comment]
增加自動顯示scroll bar
fixed in v0.1.0106

**Comment by EideWang** [comment]
仍然有破版問題
![image](https://user-images.githubusercontent.com/28863560/71860302-4e968c80-312d-11ea-92ab-926404cd3246.png)

**Comment by karateboy** [comment]
fixed in v0.1.0107
