### ISSUE TITLE
[重要] 水利建造物檢查BUG

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#82]
測站有值，卻持續出現NAN
![image](https://user-images.githubusercontent.com/28863560/71861165-63285400-3130-11ea-845f-e69573bf63d1.png)

**Comment by karateboy** [comment]
@Elvis0059 後端傳NaN的原因是? 建議前端如何處理?

**Comment by Elvis0059** [comment]
NaN是預設值，因為0是有意義的值。
資料平台Web API或Sensor有問題就會拿到NaN，請用"-"取代。
