### ISSUE TITLE
[重要] 警戒表格資料過多時的破版問題

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#83]
![image](https://user-images.githubusercontent.com/28863560/72321031-cf312c00-36dd-11ea-9d81-09ab1f5e4f3e.png)

麻煩一併處理各警戒表格潛在破版問題，謝謝

**Comment by karateboy** [comment]
fixed in v0.1.0114

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/72409022-8b066000-379f-11ea-964f-7ef3b57ab41a.png)
