### ISSUE TITLE
[登入頁面] 移除自動填帳密的快速設定

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#84]
移除自動填帳密的快速設定

**Comment by karateboy** [comment]
[如何取消自動填入密碼.pdf](https://github.com/karateboy/ylfs_demo/files/4408965/default.pdf)

**Comment by karateboy** [comment]
這是chrome的功能, 和網站無關

**Comment by karateboy** [comment]
重啟....移除預設帳號密碼
