### ISSUE TITLE
系統管理> 於主控板呈現使用者資訊，下方按鈕呈現...

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#9]
點擊"系統管理"後，於主控板呈現使用者資訊，下方按鈕呈現包括：帳號管理、雨量警戒管理、水位警戒管理、淹水警戒管理、自主防災社區管理、抽水站管理、水閘門管理、滯洪池管理、移動式抽水機管理、防汛備料管理、歷史圖資管理、歷史報表管理、相關連結管理

初步規劃如下：
其中驗收DEMO時，灰字需為變動值，黑字則可先寫死
![image](https://user-images.githubusercontent.com/28863560/69609010-91ac0d00-1063-11ea-8662-60e038feb9ee.png)

**Comment by karateboy** [comment]
已經拆分為個別issue 建議關閉

**Comment by EideWang** [comment]
不明白"已經拆分為個別issue"的意思

**Comment by karateboy** [comment]
這個設計和前面8個按鈕產出的樹狀按鈕又不同, 變成雙排按鈕. 建議改成樹狀按鈕, 統一操作風格.

**Comment by karateboy** [comment]
> 不明白"已經拆分為個別issue"的意思

issue的標題, 我以為是整個業主需求. 看內容才了解. 我把issue title改一下

**Comment by karateboy** [comment]
fix in v.0.1.1207
