### ISSUE TITLE
[雨量站infobox] 內容修正

### ISSUE THREAD

**Issue by EideWang** [karateboy/ylfs_demo#95]
![image](https://user-images.githubusercontent.com/28863560/77900209-483d2a00-72b0-11ea-9462-b5a028c2137e.png)
A. 累積總雨量(mm) ->累積降雨量(mm)
B. 移除
C. 過去10分 -> 過去10分鐘
D. 移除

**Comment by karateboy** [comment]
fixed

**Comment by EideWang** [comment]
![image](https://user-images.githubusercontent.com/28863560/78088835-fd2e2e80-73f7-11ea-9763-4618327c6d98.png)
